<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_57454ae7b0e9a',
        'title' => __('Video', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_57454c24d44d8',
                'label' => __('Type', 'municipio'),
                'name' => 'type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'embed' => __('Embed by link (YouTube or Vimeo)', 'municipio'),
                    'upload' => __('Upload video file', 'municipio'),
                ],
                'default_value' => '',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'horizontal',
                'save_other_choice' => 0,
            ],
            1 => [
                'key' => 'field_57454c5ad44db',
                'label' => __('Video: mp4', 'municipio'),
                'name' => 'video_mp4',
                'type' => 'file',
                'instructions' => __(
                    'Upload or select file from library. The only valid file format is .mp4',
                    'municipio',
                ),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_57454c24d44d8',
                            'operator' => '==',
                            'value' => 'upload',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '33.3333',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'mp4',
            ],
            2 => [
                'key' => 'field_57454c7ad44dc',
                'label' => __('Embed Link', 'municipio'),
                'name' => 'embed_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_57454c24d44d8',
                            'operator' => '==',
                            'value' => 'embed',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
            ],
            3 => [
                'key' => 'field_57454c91d44dd',
                'label' => __('Placeholder Image', 'municipio'),
                'name' => 'placeholder_image',
                'type' => 'image',
                'instructions' => __(
                    'The placeholder image is displayed before the video is played. If an embed link has been used to embed this video, a placeholder will automatically be feted from embedded service. You can still use this field, to replace the image shown.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'uploader' => '',
                'acfe_thumbnail' => 0,
                'return_format' => 'array',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ],
            4 => [
                'key' => 'field_637f27e8eb86c',
                'label' => __('Subtitles', 'municipio'),
                'name' => 'subtitles',
                'type' => 'repeater',
                'instructions' => __(
                    'Subtitles is required to be formatted as VTT files in order to work with all browsers.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_57454c24d44d8',
                            'operator' => '==',
                            'value' => 'upload',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'acfe_repeater_stylised_button' => 1,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __('Add Row', 'municipio'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_637f2831eb86d',
                        'label' => __('Subtitle File', 'municipio'),
                        'name' => 'file',
                        'type' => 'file',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'uploader' => '',
                        'return_format' => 'url',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'vtt',
                        'library' => 'all',
                        'parent_repeater' => 'field_637f27e8eb86c',
                    ],
                    1 => [
                        'key' => 'field_637f2869eb86e',
                        'label' => __('Language', 'municipio'),
                        'name' => 'language',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'ab' => __('Abkhaz (аҧсуа)', 'municipio'),
                            'aa' => __('Afar (Afaraf)', 'municipio'),
                            'af' => __('Afrikaans (Afrikaans)', 'municipio'),
                            'ak' => __('Akan (Akan)', 'municipio'),
                            'sq' => __('Albanian (Shqip)', 'municipio'),
                            'am' => __('Amharic (አማርኛ)', 'municipio'),
                            'ar' => __('Arabic (العربية)', 'municipio'),
                            'an' => __('Aragonese (Aragonés)', 'municipio'),
                            'hy' => __('Armenian (Հայերեն)', 'municipio'),
                            'as' => __('Assamese (অসমীয়া)', 'municipio'),
                            'av' => __('Avaric (авар мацӀ, магӀарул мацӀ)', 'municipio'),
                            'ae' => __('Avestan (avesta)', 'municipio'),
                            'ay' => __('Aymara (aymar aru)', 'municipio'),
                            'az' => __('Azerbaijani (azərbaycan dili)', 'municipio'),
                            'bm' => __('Bambara (bamanankan)', 'municipio'),
                            'ba' => __('Bashkir (башҡорт теле)', 'municipio'),
                            'eu' => __('Basque (euskara, euskera)', 'municipio'),
                            'be' => __('Belarusian (Беларуская)', 'municipio'),
                            'bn' => __('Bengali (বাংলা)', 'municipio'),
                            'bh' => __('Bihari (भोजपुरी)', 'municipio'),
                            'bi' => __('Bislama (Bislama)', 'municipio'),
                            'bs' => __('Bosnian (bosanski jezik)', 'municipio'),
                            'br' => __('Breton (brezhoneg)', 'municipio'),
                            'bg' => __('Bulgarian (български език)', 'municipio'),
                            'my' => __('Burmese (ဗမာစာ)', 'municipio'),
                            'ca' => __('Catalan (Català)', 'municipio'),
                            'ch' => __('Chamorro (Chamoru)', 'municipio'),
                            'ce' => __('Chechen (нохчийн мотт)', 'municipio'),
                            'ny' => __('Chichewa (chiCheŵa, chinyanja)', 'municipio'),
                            'zh' => __('Chinese (中文 (Zhōngwén), 汉语, 漢語)', 'municipio'),
                            'cv' => __('Chuvash (чӑваш чӗлхи)', 'municipio'),
                            'kw' => __('Cornish (Kernewek)', 'municipio'),
                            'co' => __('Corsican (corsu, lingua corsa)', 'municipio'),
                            'cr' => __('Cree (ᓀᐦᐃᔭᐍᐏᐣ)', 'municipio'),
                            'hr' => __('Croatian (hrvatski)', 'municipio'),
                            'cs' => __('Czech (česky, čeština)', 'municipio'),
                            'da' => __('Danish (dansk)', 'municipio'),
                            'dv' => __('Divehi (ދިވެހި)', 'municipio'),
                            'nl' => __('Dutch (Nederlands, Vlaams)', 'municipio'),
                            'en' => __('English (English)', 'municipio'),
                            'eo' => __('Esperanto (Esperanto)', 'municipio'),
                            'et' => __('Estonian (eesti, eesti keel)', 'municipio'),
                            'ee' => __('Ewe (Eʋegbe)', 'municipio'),
                            'fo' => __('Faroese (føroyskt)', 'municipio'),
                            'fj' => __('Fijian (vosa Vakaviti)', 'municipio'),
                            'fi' => __('Finnish (suomi, suomen kieli)', 'municipio'),
                            'fr' => __('French (français, langue française)', 'municipio'),
                            'ff' => __('Fula (Fulfulde, Pulaar, Pular)', 'municipio'),
                            'gl' => __('Galician (Galego)', 'municipio'),
                            'ka' => __('Georgian (ქართული)', 'municipio'),
                            'de' => __('German (Deutsch)', 'municipio'),
                            'el' => __('Greek (Ελληνικά)', 'municipio'),
                            'gn' => __('Guaraní (Avañeẽ)', 'municipio'),
                            'gu' => __('Gujarati (ગુજરાતી)', 'municipio'),
                            'ht' => __('Haitian (Kreyòl ayisyen)', 'municipio'),
                            'ha' => __('Hausa (Hausa, هَوُسَ)', 'municipio'),
                            'he' => __('Hebrew (modern) (עברית)', 'municipio'),
                            'hz' => __('Herero (Otjiherero)', 'municipio'),
                            'hi' => __('Hindi (हिन्दी, हिंदी)', 'municipio'),
                            'ho' => __('Hiri Motu (Hiri Motu)', 'municipio'),
                            'hu' => __('Hungarian (Magyar)', 'municipio'),
                            'ia' => __('Interlingua (Interlingua)', 'municipio'),
                            'id' => __('Indonesian (Bahasa Indonesia)', 'municipio'),
                            'ie' => __(
                                'Interlingue (Originally called Occidental; then Interlingue after WWII)',
                                'municipio',
                            ),
                            'ga' => __('Irish (Gaeilge)', 'municipio'),
                            'ig' => __('Igbo (Asụsụ Igbo)', 'municipio'),
                            'ik' => __('Inupiaq (Iñupiaq, Iñupiatun)', 'municipio'),
                            'io' => __('Ido (Ido)', 'municipio'),
                            'is' => __('Icelandic (Íslenska)', 'municipio'),
                            'it' => __('Italian (Italiano)', 'municipio'),
                            'iu' => __('Inuktitut (ᐃᓄᒃᑎᑐᑦ)', 'municipio'),
                            'ja' => __('Japanese (日本語 (にほんご／にっぽんご))', 'municipio'),
                            'jv' => __('Javanese (basa Jawa)', 'municipio'),
                            'kl' => __('Kalaallisut (kalaallisut, kalaallit oqaasii)', 'municipio'),
                            'kn' => __('Kannada (ಕನ್ನಡ)', 'municipio'),
                            'kr' => __('Kanuri (Kanuri)', 'municipio'),
                            'ks' => __('Kashmiri (कश्मीरी, كشميري‎)', 'municipio'),
                            'kk' => __('Kazakh (Қазақ тілі)', 'municipio'),
                            'km' => __('Khmer (ភាសាខ្មែរ)', 'municipio'),
                            'ki' => __('Kikuyu (Gĩkũyũ)', 'municipio'),
                            'rw' => __('Kinyarwanda (Ikinyarwanda)', 'municipio'),
                            'ky' => __('Kirghiz (кыргыз тили)', 'municipio'),
                            'kv' => __('Komi (коми кыв)', 'municipio'),
                            'kg' => __('Kongo (KiKongo)', 'municipio'),
                            'ko' => __('Korean (한국어 (韓國語), 조선말 (朝鮮語))', 'municipio'),
                            'ku' => __('Kurdish (Kurdî, كوردی‎)', 'municipio'),
                            'kj' => __('Kwanyama (Kuanyama)', 'municipio'),
                            'la' => __('Latin (latine, lingua latina)', 'municipio'),
                            'lb' => __('Luxembourgish (Lëtzebuergesch)', 'municipio'),
                            'lg' => __('Luganda (Luganda)', 'municipio'),
                            'li' => __('Limburgish (Limburgs)', 'municipio'),
                            'ln' => __('Lingala (Lingála)', 'municipio'),
                            'lo' => __('Lao (ພາສາລາວ)', 'municipio'),
                            'lt' => __('Lithuanian (lietuvių kalba)', 'municipio'),
                            'lu' => __('Luba-Katanga ()', 'municipio'),
                            'lv' => __('Latvian (latviešu valoda)', 'municipio'),
                            'gv' => __('Manx (Gaelg, Gailck)', 'municipio'),
                            'mk' => __('Macedonian (македонски јазик)', 'municipio'),
                            'mg' => __('Malagasy (Malagasy fiteny)', 'municipio'),
                            'ms' => __('Malay (bahasa Melayu, بهاس ملايو‎)', 'municipio'),
                            'ml' => __('Malayalam (മലയാളം)', 'municipio'),
                            'mt' => __('Maltese (Malti)', 'municipio'),
                            'mi' => __('Māori (te reo Māori)', 'municipio'),
                            'mr' => __('Marathi (Marāṭhī) (मराठी)', 'municipio'),
                            'mh' => __('Marshallese (Kajin M̧ajeļ)', 'municipio'),
                            'mn' => __('Mongolian (монгол)', 'municipio'),
                            'na' => __('Nauru (Ekakairũ Naoero)', 'municipio'),
                            'nv' => __('Navajo (Diné bizaad, Dinékʼehǰí)', 'municipio'),
                            'nb' => __('Norwegian Bokmål (Norsk bokmål)', 'municipio'),
                            'nd' => __('North Ndebele (isiNdebele)', 'municipio'),
                            'ne' => __('Nepali (नेपाली)', 'municipio'),
                            'ng' => __('Ndonga (Owambo)', 'municipio'),
                            'nn' => __('Norwegian Nynorsk (Norsk nynorsk)', 'municipio'),
                            'no' => __('Norwegian (Norsk)', 'municipio'),
                            'ii' => __('Nuosu (ꆈꌠ꒿ Nuosuhxop)', 'municipio'),
                            'nr' => __('South Ndebele (isiNdebele)', 'municipio'),
                            'oc' => __('Occitan (Occitan)', 'municipio'),
                            'oj' => __('Ojibwe (ᐊᓂᔑᓈᐯᒧᐎᓐ)', 'municipio'),
                            'cu' => __('Old Church Slavonic (ѩзыкъ словѣньскъ)', 'municipio'),
                            'om' => __('Oromo (Afaan Oromoo)', 'municipio'),
                            'or' => __('Oriya (ଓଡ଼ିଆ)', 'municipio'),
                            'os' => __('Ossetian (ирон æвзаг)', 'municipio'),
                            'pa' => __('Panjabi (ਪੰਜਾਬੀ, پنجابی‎)', 'municipio'),
                            'pi' => __('Pāli (पाऴि)', 'municipio'),
                            'fa' => __('Persian (فارسی)', 'municipio'),
                            'pl' => __('Polish (polski)', 'municipio'),
                            'ps' => __('Pashto (پښتو)', 'municipio'),
                            'pt' => __('Portuguese (Português)', 'municipio'),
                            'qu' => __('Quechua (Runa Simi, Kichwa)', 'municipio'),
                            'rm' => __('Romansh (rumantsch grischun)', 'municipio'),
                            'rn' => __('Kirundi (kiRundi)', 'municipio'),
                            'ro' => __('Romanian (română)', 'municipio'),
                            'ru' => __('Russian (русский язык)', 'municipio'),
                            'sa' => __('Sanskrit (Saṁskṛta) (संस्कृतम्)', 'municipio'),
                            'sc' => __('Sardinian (sardu)', 'municipio'),
                            'sd' => __('Sindhi (सिन्धी, سنڌي، سندھی‎)', 'municipio'),
                            'se' => __('Northern Sami (Davvisámegiella)', 'municipio'),
                            'sm' => __('Samoan (gagana faa Samoa)', 'municipio'),
                            'sg' => __('Sango (yângâ tî sängö)', 'municipio'),
                            'sr' => __('Serbian (српски језик)', 'municipio'),
                            'gd' => __('Scottish Gaelic (Gàidhlig)', 'municipio'),
                            'sn' => __('Shona (chiShona)', 'municipio'),
                            'si' => __('Sinhala (සිංහල)', 'municipio'),
                            'sk' => __('Slovak (slovenčina)', 'municipio'),
                            'sl' => __('Slovene (slovenščina)', 'municipio'),
                            'so' => __('Somali (Soomaaliga, af Soomaali)', 'municipio'),
                            'st' => __('Southern Sotho (Sesotho)', 'municipio'),
                            'es' => __('Spanish (español, castellano)', 'municipio'),
                            'su' => __('Sundanese (Basa Sunda)', 'municipio'),
                            'sw' => __('Swahili (Kiswahili)', 'municipio'),
                            'ss' => __('Swati (SiSwati)', 'municipio'),
                            'sv' => __('Swedish (svenska)', 'municipio'),
                            'ta' => __('Tamil (தமிழ்)', 'municipio'),
                            'te' => __('Telugu (తెలుగు)', 'municipio'),
                            'tg' => __('Tajik (тоҷикӣ, toğikī, تاجیکی‎)', 'municipio'),
                            'th' => __('Thai (ไทย)', 'municipio'),
                            'ti' => __('Tigrinya (ትግርኛ)', 'municipio'),
                            'bo' => __('Tibetan Standard (བོད་ཡིག)', 'municipio'),
                            'tk' => __('Turkmen (Türkmen, Түркмен)', 'municipio'),
                            'tl' => __('Tagalog (Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔)', 'municipio'),
                            'tn' => __('Tswana (Setswana)', 'municipio'),
                            'to' => __('Tonga (Tonga Islands) (faka Tonga)', 'municipio'),
                            'tr' => __('Turkish (Türkçe)', 'municipio'),
                            'ts' => __('Tsonga (Xitsonga)', 'municipio'),
                            'tt' => __('Tatar (татарча, tatarça, تاتارچا‎)', 'municipio'),
                            'tw' => __('Twi (Twi)', 'municipio'),
                            'ty' => __('Tahitian (Reo Tahiti)', 'municipio'),
                            'ug' => __('Uighur (Uyƣurqə, ئۇيغۇرچە‎)', 'municipio'),
                            'uk' => __('Ukrainian (українська)', 'municipio'),
                            'ur' => __('Urdu (اردو)', 'municipio'),
                            'uz' => __('Uzbek (zbek, Ўзбек, أۇزبېك‎)', 'municipio'),
                            've' => __('Venda (Tshivenḓa)', 'municipio'),
                            'vi' => __('Vietnamese (Tiếng Việt)', 'municipio'),
                            'vo' => __('Volapük (Volapük)', 'municipio'),
                            'wa' => __('Walloon (Walon)', 'municipio'),
                            'cy' => __('Welsh (Cymraeg)', 'municipio'),
                            'wo' => __('Wolof (Wollof)', 'municipio'),
                            'fy' => __('Western Frisian (Frysk)', 'municipio'),
                            'xh' => __('Xhosa (isiXhosa)', 'municipio'),
                            'yi' => __('Yiddish (ייִדיש)', 'municipio'),
                            'yo' => __('Yoruba (Yorùbá)', 'municipio'),
                            'za' => __('Zhuang (Saɯ cueŋƅ, Saw cuengh)', 'municipio'),
                        ],
                        'default_value' => __('sv', 'municipio'),
                        'return_format' => 'array',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_637f27e8eb86c',
                    ],
                ],
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-video',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/video',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
