<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5729f4d3e7c7a',
    'title' => __('Wordpress Widget', 'modularity'),
    'fields' => array(
        0 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'WP_Widget_Archives' => __('Arkiv', 'modularity'),
                'WP_Widget_Calendar' => __('Kalender', 'modularity'),
                'WP_Widget_Categories' => __('Kategorier', 'modularity'),
                'WP_Widget_Meta' => __('Meta', 'modularity'),
                'WP_Widget_Pages' => __('Sidor', 'modularity'),
                'WP_Widget_Recent_Comments' => __('Senaste kommentarerna', 'modularity'),
                'WP_Widget_Recent_Posts' => __('Senaste inläggen', 'modularity'),
                'WP_Widget_RSS' => __('RSS', 'modularity'),
                'WP_Widget_Search' => __('Sök', 'modularity'),
                'WP_Widget_Tag_Cloud' => __('Taggmoln', 'modularity'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_572a06dd9d06c',
            'label' => __('Widget Type', 'modularity'),
            'name' => 'mod_standard_widget_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'message' => __('There are no options available for this widget type.<br> <style>.acf-field-57309aa0b176d {background-color: #FFDFDF;}</style>', 'modularity'),
            'esc_html' => 0,
            'new_lines' => '',
            'key' => 'field_57309aa0b176d',
            'label' => __('No options avabile', 'modularity'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Calendar',
                    ),
                ),
                1 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Meta',
                    ),
                ),
                2 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Search',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'layout' => 'horizontal',
            'choices' => array(
                0 => __('No', 'modularity'),
                1 => __('Yes', 'modularity'),
            ),
            'default_value' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_5730a1f85e023',
            'label' => __('Show number of items indicator', 'modularity'),
            'name' => 'wp_widget_archive_count',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Archives',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        3 => array(
            'layout' => 'horizontal',
            'choices' => array(
                0 => __('No', 'modularity'),
                1 => __('Yes', 'modularity'),
            ),
            'default_value' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_57319d35a5915',
            'label' => __('Show as dropdown list', 'modularity'),
            'name' => 'wp_widget_archive_dropdown',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Archives',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        4 => array(
            'layout' => 'horizontal',
            'choices' => array(
                0 => __('No', 'modularity'),
                1 => __('Yes', 'modularity'),
            ),
            'default_value' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_57319e7e4900e',
            'label' => __('Show number of category items indicator', 'modularity'),
            'name' => 'wp_widget_cat_count',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Categories',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33,333',
                'class' => '',
                'id' => '',
            ),
        ),
        5 => array(
            'layout' => 'horizontal',
            'choices' => array(
                0 => __('No', 'modularity'),
                1 => __('Yes', 'modularity'),
            ),
            'default_value' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_5731aa7f0f0f8',
            'label' => __('Show as hierarchial list', 'modularity'),
            'name' => 'wp_widget_cat_hierarchical',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Categories',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33,333',
                'class' => '',
                'id' => '',
            ),
        ),
        6 => array(
            'layout' => 'horizontal',
            'choices' => array(
                0 => __('No', 'modularity'),
                1 => __('Yes', 'modularity'),
            ),
            'default_value' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_5731aaac9c7d2',
            'label' => __('Show as dropdown', 'modularity'),
            'name' => 'wp_widget_cat_dropdown',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Categories',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33,333',
                'class' => '',
                'id' => '',
            ),
        ),
        7 => array(
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                'post_title' => __('Titel', 'modularity'),
                'menu_order' => __('Menu order', 'modularity'),
                'ID' => __('Page ID', 'modularity'),
            ),
            'default_value' => array(
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_5731e69671076',
            'label' => __('Sort by', 'modularity'),
            'name' => 'wp_widget_pages_sort_by',
            'type' => 'select',
            'instructions' => __('Select how to sort the pages', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Pages',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'disabled' => 0,
            'readonly' => 0,
        ),
        8 => array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5731e78c71077',
            'label' => __('Exclude', 'modularity'),
            'name' => 'wp_widget_pages_exclude',
            'type' => 'text',
            'instructions' => __('ID:s of pages to exclude. Separated by comma.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Pages',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        9 => array(
            'default_value' => 5,
            'min' => 1,
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5731e8cf25b42',
            'label' => __('Number of comments to show', 'modularity'),
            'name' => 'wp_widget_comments_comments',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Recent_Comments',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        10 => array(
            'default_value' => 5,
            'min' => '',
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5731e9c32cd95',
            'label' => __('Number of posts to show', 'modularity'),
            'name' => 'wp_widget_posts_number',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Recent_Posts',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        11 => array(
            'default_value' => '',
            'placeholder' => '',
            'key' => 'field_5731ea87eae83',
            'label' => __('RSS Url', 'modularity'),
            'name' => 'wp_widget_rss_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_RSS',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        12 => array(
            'default_value' => 5,
            'min' => '',
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5731ea9beae84',
            'label' => __('Items to show', 'modularity'),
            'name' => 'wp_widget_rss_items',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_RSS',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 25,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        13 => array(
            'default_value' => 0,
            'message' => __('Yes, show summary', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_5731eab4eae85',
            'label' => __('Show summary', 'modularity'),
            'name' => 'wp_widget_rss_summary',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_RSS',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 25,
                'class' => '',
                'id' => '',
            ),
        ),
        14 => array(
            'default_value' => 0,
            'message' => __('Yes, show author', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_5731eaceeae86',
            'label' => __('Visa författare', 'modularity'),
            'name' => 'wp_widget_rss_author',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_RSS',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 25,
                'class' => '',
                'id' => '',
            ),
        ),
        15 => array(
            'default_value' => 0,
            'message' => __('Yes, show date', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_5731eae5eae87',
            'label' => __('Show date', 'modularity'),
            'name' => 'wp_widget_rss_date',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_RSS',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 25,
                'class' => '',
                'id' => '',
            ),
        ),
        16 => array(
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                'category' => __('Kategorier', 'modularity'),
                'post_tag' => __('Taggar', 'modularity'),
                'link_category' => __('Länkkategorier', 'modularity'),
                'listing-category' => __('Kategori', 'modularity'),
                'listing-places' => __('Plats', 'modularity'),
                'amne' => __('Ämne', 'modularity'),
            ),
            'default_value' => array(
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_5731ebd018370',
            'label' => __('Taxonomy', 'modularity'),
            'name' => 'wp_widget_tag_cloud_taxonomy',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_572a06dd9d06c',
                        'operator' => '==',
                        'value' => 'WP_Widget_Tag_Cloud',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'disabled' => 0,
            'readonly' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-wpwidget',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'custom_fields',
        4 => 'discussion',
        5 => 'comments',
        6 => 'revisions',
        7 => 'slug',
        8 => 'author',
        9 => 'format',
        10 => 'page_attributes',
        11 => 'featured_image',
        12 => 'categories',
        13 => 'tags',
        14 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
    'modified' => 1462889442,
    'local' => 'php',
));
}