<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_609b788ad04bb',
        'title' => __('Curator Social Media', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_609b7d2ba3004',
                'label' => __('Number of posts', 'municipio'),
                'name' => 'number_of_posts',
                'type' => 'number',
                'instructions' => __('Set the number items to show.', 'municipio'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'default_value' => 12,
                'min' => 4,
                'max' => 24,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ],
            1 => [
                'key' => 'field_63edf811d3a68',
                'label' => __('Layout', 'municipio'),
                'name' => 'layout',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'choices' => [
                    'card' => __('Card', 'municipio'),
                    'block' => __('Block', 'municipio'),
                ],
                'default_value' => __('card', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            2 => [
                'key' => 'field_63ee10add6ed6',
                'label' => __('Columns', 'municipio'),
                'name' => 'columns',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'choices' => [
                    3 => __('3', 'municipio'),
                    4 => __('4', 'municipio'),
                ],
                'default_value' => false,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            3 => [
                'key' => 'field_63ff2bc5ce2c6',
                'label' => __('Grid gutter', 'municipio'),
                'name' => 'gutter',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63edf811d3a68',
                            'operator' => '==',
                            'value' => 'block',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'message' => __('No space between the posts in the grid', 'municipio'),
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            4 => [
                'key' => 'field_63ee0a94197d1',
                'label' => __('Ratio', 'municipio'),
                'name' => 'ratio',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63edf811d3a68',
                            'operator' => '==',
                            'value' => 'block',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'choices' => [
                    '1:1' => __('1:1', 'municipio'),
                    '4:3' => __('4:3', 'municipio'),
                    '12:6' => __('12:6', 'municipio'),
                ],
                'default_value' => __('1:1', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            5 => [
                'key' => 'field_609b7894869ce',
                'label' => __('Embed Code', 'municipio'),
                'name' => 'embed_code',
                'type' => 'textarea',
                'instructions' => __(
                    'Add your curator embed code here. Thios should be the full javascript. Appeance settings in the javascript configurator will not apply.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
            ],
            6 => [
                'key' => 'field_609baae15568c',
                'label' => __('Usage of the curator social media integration', 'municipio'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'aria-label' => '',
                'message' => __('This is an integration module for curator.io. The module requires an account at the service. 

To integrate a feed, head over to <a href="https://curator.io" target="_blank">curator.io</a> (will open in a new window) and follow the steps below. We assume that you already have an account, with a connected feed. 

1. Login to your account. 
2. Click on "style" in the sidebar navigation. 
3. Click on "publish feed" (style won\'t matter). 
4. Paste the embed code in the field above. 
5. Save. Your feed should no be displayed.', 'modularity'),
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ],
            7 => [
                'key' => 'field_643fcdc3b8269',
                'label' => __('Show powered by', 'municipio'),
                'name' => 'show_powered_by',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => __(
                    'Uncheck to disable the powered by link. It is required to display this link, if free version is used.',
                    'municipio',
                ),
                'default_value' => 1,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-curator',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/curator',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
