<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_575a842dd1283',
        'title' => __('Notice settings', 'municipio'),
        'fields' => array(
            0 => array(
                'key' => 'field_575a8454ea3b4',
                'label' => __('Type', 'municipio'),
                'name' => 'notice_type',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'success' => __('Success (green)', 'municipio'),
                    'info' => __('Info (black)', 'municipio'),
                    'warning' => __('Warning (yellow)', 'municipio'),
                    'danger' => __('Danger (red)', 'municipio'),
                ),
                'default_value' => __('success', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            1 => array(
                'key' => 'field_575a8436ea3b3',
                'label' => __('Notice', 'municipio'),
                'name' => 'notice_text',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            2 => array(
                'key' => 'field_67a3376a096cd',
                'label' => __('Include link', 'municipio'),
                'name' => 'include_link',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => __('Yes', 'municipio'),
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            3 => array(
                'key' => 'field_67a33791096ce',
                'label' => __('Link', 'municipio'),
                'name' => 'link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_67a3376a096cd',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            4 => array(
                'key' => 'field_67a337b2096cf',
                'label' => __('Link position', 'municipio'),
                'name' => 'link_position',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_67a3376a096cd',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'aside' => __('Aside text', 'municipio'),
                    'below' => __('Below text', 'municipio'),
                ),
                'default_value' => __('below', 'municipio'),
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'horizontal',
                'save_other_choice' => 0,
            ),
            5 => array(
                'key' => 'field_67ab264cf9291',
                'label' => __('Dismissible', 'municipio'),
                'name' => 'dismissible',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => __('Yes', 'municipio'),
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            6 => array(
                'key' => 'field_67ab2686f9293',
                'label' => __('Dismissal time', 'municipio'),
                'name' => 'dismissal_time',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    0 => array(
                        0 => array(
                            'field' => 'field_67ab264cf9291',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'session' => __('Dismissed until user restarts browser', 'municipio'),
                    'permanent' => __('Dismissed "forever"', 'municipio'),
                    'immediate' => __('Dismissed until page reload', 'municipio'),
                ),
                'default_value' => __('session', 'municipio'),
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'horizontal',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            0 => array(
                0 => array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-notice',
                ),
            ),
            1 => array(
                0 => array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/notice',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
}
