<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_602400d904b59',
        'title' => __('Map', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_64ad64dacdb16',
                'label' => __('Map type', 'municipio'),
                'name' => 'map_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'default' => __('Embedded', 'municipio'),
                    'openStreetMap' => __('Open Street Map', 'municipio'),
                ],
                'default_value' => __('default', 'municipio'),
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ],
            1 => [
                'key' => 'field_602400dda5195',
                'label' => __('Map URL', 'municipio'),
                'name' => 'map_url',
                'type' => 'url',
                'instructions' => __(
                    '<span style="color: #f00;">Din länk måste starta med http<strong>s</strong>:// för att kunna visas på webbplatsen.</span>',
                    'municipio',
                ),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
            ],
            2 => [
                'key' => 'field_602415a77f5da',
                'label' => __('Description', 'municipio'),
                'name' => 'map_description',
                'type' => 'textarea',
                'instructions' => __('Describe the contents of this map (not shown)', 'municipio'),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '70',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'rows' => 3,
                'placeholder' => '',
                'new_lines' => '',
            ],
            3 => [
                'key' => 'field_602401605c3f6',
                'label' => __('Miniumum Height', 'municipio'),
                'name' => 'height',
                'type' => 'range',
                'instructions' => __('Set a minumum height', 'municipio'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 400,
                'min' => 256,
                'max' => 720,
                'step' => 16,
                'prepend' => '',
                'append' => __('px', 'municipio'),
            ],
            4 => [
                'key' => 'field_602459632b135',
                'label' => __('Show button', 'municipio'),
                'name' => 'show_button',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            5 => [
                'key' => 'field_602459d52b136',
                'label' => __('Button label', 'municipio'),
                'name' => 'button_label',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_602459632b135',
                            'operator' => '==',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => __('Show large version', 'municipio'),
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            6 => [
                'key' => 'field_602459ee2b137',
                'label' => __('Button url', 'municipio'),
                'name' => 'button_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_602459632b135',
                            'operator' => '==',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '70',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
            ],
            7 => [
                'key' => 'field_60520ab40ffd7',
                'label' => __('Extra info', 'municipio'),
                'name' => 'more_info_button',
                'type' => 'true_false',
                'instructions' => __(
                    'Do you want to add Extra info?
The information will be placed in a card on the right side of the map.',
                    'modularity',
                ),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => __('The extra info card is disabled by default', 'municipio'),
                'default_value' => 0,
                'ui_on_text' => __('Enabled', 'municipio'),
                'ui_off_text' => __('Disabled', 'municipio'),
                'ui' => 1,
            ],
            8 => [
                'key' => 'field_6052101f0ad06',
                'label' => __('Extra info title', 'municipio'),
                'name' => 'more_info_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_60520ab40ffd7',
                            'operator' => '==',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            9 => [
                'key' => 'field_6052087c0ffd6',
                'label' => __('Extra information', 'municipio'),
                'name' => 'more_info',
                'type' => 'wysiwyg',
                'instructions' => __('Add extra information such as opening hours or map location.', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_60520ab40ffd7',
                            'operator' => '==',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'default',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'delay' => 0,
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 1,
            ],
            10 => [
                'key' => 'field_64c77830c32aa',
                'label' => __('Start position', 'municipio'),
                'name' => 'osm_start_position',
                'type' => 'google_map',
                'instructions' => __('Sets the start position of the map', 'municipio'),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'openStreetMap',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'center_lat' => '59.32932',
                'center_lng' => '18.06858',
                'zoom' => '',
                'height' => 500,
            ],
            11 => [
                'key' => 'field_64ad5fd710885',
                'label' => __('Map markers', 'municipio'),
                'name' => 'osm_markers',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_64ad64dacdb16',
                            'operator' => '==',
                            'value' => 'openStreetMap',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __('Lägg till rad', 'municipio'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_64ad60190d5a5',
                        'label' => __('Title', 'municipio'),
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ad5fd710885',
                    ],
                    1 => [
                        'key' => 'field_64ad60b00d5a6',
                        'label' => __('Description', 'municipio'),
                        'name' => 'description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'acfe_textarea_code' => 0,
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'field_64ad5fd710885',
                    ],
                    2 => [
                        'key' => 'field_64ad60ed0d5a8',
                        'label' => __('Link text', 'municipio'),
                        'name' => 'link_text',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ad5fd710885',
                    ],
                    3 => [
                        'key' => 'field_64ad60bd0d5a7',
                        'label' => __('Url', 'municipio'),
                        'name' => 'url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'parent_repeater' => 'field_64ad5fd710885',
                    ],
                    4 => [
                        'key' => 'field_64ad61220d5a9',
                        'label' => __('Position', 'municipio'),
                        'name' => 'position',
                        'type' => 'google_map',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'center_lat' => '',
                        'center_lng' => '',
                        'zoom' => '',
                        'height' => 500,
                        'parent_repeater' => 'field_64ad5fd710885',
                    ],
                ],
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-map',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/map',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
