<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_614b3f1a751bf',
    'title' => __('Hero', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_63ca5ed1394e1',
            'label' => __('Display as', 'modularity'),
            'name' => 'mod_hero_display_as',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default' => __('Default', 'modularity'),
                'twoColumn' => __('Two columns', 'modularity'),
                'callToActions' => __('Call to Actions', 'modularity'),
            ),
            'default_value' => __('default', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        1 => array(
            'key' => 'field_63ca60c84bb03',
            'label' => __('Background color', 'modularity'),
            'name' => 'mod_hero_background_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '==',
                        'value' => 'twoColumn',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('rgba(255,255,255,0.0)', 'modularity'),
            'enable_opacity' => 1,
            'return_format' => 'string',
        ),
        2 => array(
            'key' => 'field_63d7907b6805a',
            'label' => __('Text color', 'modularity'),
            'name' => 'mod_hero_text_color',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '==',
                        'value' => 'twoColumn',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'white' => __('White', 'modularity'),
                'black' => __('Black', 'modularity'),
            ),
            'default_value' => __('white', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        3 => array(
            'key' => 'field_614b3f1e6ed4a',
            'label' => __('Byline', 'modularity'),
            'name' => 'mod_hero_byline',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('A clear byline, to say something else.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '!=',
                        'value' => 'callToActions',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_63d78c4897632',
            'label' => __('Meta', 'modularity'),
            'name' => 'mod_hero_meta',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '!=',
                        'value' => 'callToActions',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        5 => array(
            'key' => 'field_614b3f5a6ed4b',
            'label' => __('Body', 'modularity'),
            'name' => 'mod_hero_body',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('A short and concise text about this site. What\'s it about? Maximum 500 characters.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'render_type' => '',
            'filter_context' => '',
            'share_option' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 500,
            'rows' => 4,
            'new_lines' => '',
            'wp_object' => '',
            'acfe_textarea_code' => 0,
        ),
        6 => array(
            'key' => 'field_62c3f89f983b1',
            'label' => __('Background type', 'modularity'),
            'name' => 'mod_hero_background_type',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'image' => __('Image', 'modularity'),
                'video' => __('Video', 'modularity'),
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        7 => array(
            'key' => 'field_614b3f786ed4c',
            'label' => __('Background image', 'modularity'),
            'name' => 'mod_hero_background_image',
            'aria-label' => '',
            'type' => 'focuspoint',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_62c3f89f983b1',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'preview_size' => 'large',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
        ),
        8 => array(
            'key' => 'field_62c3f8fa57719',
            'label' => __('Background video', 'modularity'),
            'name' => 'mod_hero_background_video',
            'aria-label' => '',
            'type' => 'file',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_62c3f89f983b1',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
            'uploader' => '',
        ),
        9 => array(
            'key' => 'field_646f25456ea80',
            'label' => __('Poster image', 'modularity'),
            'name' => 'mod_hero_poster_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_62c3f89f983b1',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'acfe_thumbnail' => 0,
            'return_format' => 'array',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
            'library' => 'all',
        ),
        10 => array(
            'key' => 'field_684bf60873e57',
            'label' => __('Display media above content', 'modularity'),
            'name' => 'mod_hero_media_first',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '==',
                        'value' => 'callToActions',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        11 => array(
            'key' => 'field_614b43a186da4',
            'label' => __('Size', 'modularity'),
            'name' => 'mod_hero_size',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'small' => __('Small', 'modularity'),
                'normal' => __('Normal', 'modularity'),
                'large' => __('Large', 'modularity'),
            ),
            'default_value' => __('normal', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        12 => array(
            'key' => 'field_6848393a785be',
            'label' => __('Buttons', 'modularity'),
            'name' => 'mod_hero_buttons',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_63ca5ed1394e1',
                        'operator' => '==',
                        'value' => 'callToActions',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 1,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add Call to Action button', 'modularity'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6848395c785bf',
                    'label' => __('Link', 'modularity'),
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'parent_repeater' => 'field_6848393a785be',
                ),
                1 => array(
                    'key' => 'field_68483977785c0',
                    'label' => __('Type', 'modularity'),
                    'name' => 'type',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'basic' => __('Basic', 'modularity'),
                        'filled' => __('Filled', 'modularity'),
                        'outlined' => __('Outlined', 'modularity'),
                    ),
                    'default_value' => __('filled', 'modularity'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_6848393a785be',
                ),
                2 => array(
                    'key' => 'field_68483b78fe5b6',
                    'label' => __('Color', 'modularity'),
                    'name' => 'color',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'default' => __('Default', 'modularity'),
                        'primary' => __('Primary', 'modularity'),
                        'secondary' => __('Secondary', 'modularity'),
                    ),
                    'default_value' => __('primary', 'modularity'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_6848393a785be',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-hero',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/hero',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}