<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57454ae7b0e9a',
    'title' => __('Video', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_57454c24d44d8',
            'label' => __('Type', 'modularity'),
            'name' => 'type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'embed' => __('Embed by link (YouTube or Vimeo)', 'modularity'),
                'upload' => __('Upload video file', 'modularity'),
            ),
            'default_value' => '',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        1 => array(
            'key' => 'field_57454c5ad44db',
            'label' => __('Video: mp4', 'modularity'),
            'name' => 'video_mp4',
            'type' => 'file',
            'instructions' => __('Upload or select file from library. The only valid file format is .mp4', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'upload',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33.3333',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
        ),
        2 => array(
            'key' => 'field_57454c7ad44dc',
            'label' => __('Embed Link', 'modularity'),
            'name' => 'embed_link',
            'type' => 'url',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'embed',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_57454c91d44dd',
            'label' => __('Placeholder Image', 'modularity'),
            'name' => 'placeholder_image',
            'type' => 'image',
            'instructions' => __('The placeholder image is displayed before the video is played. If an embed link has been used to embed this video, a placeholder will automatically be feted from embedded service. You can still use this field, to replace the image shown.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'acfe_thumbnail' => 0,
            'return_format' => 'array',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        4 => array(
            'key' => 'field_637f27e8eb86c',
            'label' => __('Subtitles', 'modularity'),
            'name' => 'subtitles',
            'type' => 'repeater',
            'instructions' => __('Subtitles is required to be formatted as VTT files in order to work with all browsers.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'upload',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 1,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add Row', 'modularity'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_637f2831eb86d',
                    'label' => __('Subtitle File', 'modularity'),
                    'name' => 'file',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'return_format' => 'url',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => 'vtt',
                    'library' => 'all',
                    'parent_repeater' => 'field_637f27e8eb86c',
                ),
                1 => array(
                    'key' => 'field_637f2869eb86e',
                    'label' => __('Language', 'modularity'),
                    'name' => 'language',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'ab' => __('Abkhaz (аҧсуа)', 'modularity'),
                        'aa' => __('Afar (Afaraf)', 'modularity'),
                        'af' => __('Afrikaans (Afrikaans)', 'modularity'),
                        'ak' => __('Akan (Akan)', 'modularity'),
                        'sq' => __('Albanian (Shqip)', 'modularity'),
                        'am' => __('Amharic (አማርኛ)', 'modularity'),
                        'ar' => __('Arabic (العربية)', 'modularity'),
                        'an' => __('Aragonese (Aragonés)', 'modularity'),
                        'hy' => __('Armenian (Հայերեն)', 'modularity'),
                        'as' => __('Assamese (অসমীয়া)', 'modularity'),
                        'av' => __('Avaric (авар мацӀ, магӀарул мацӀ)', 'modularity'),
                        'ae' => __('Avestan (avesta)', 'modularity'),
                        'ay' => __('Aymara (aymar aru)', 'modularity'),
                        'az' => __('Azerbaijani (azərbaycan dili)', 'modularity'),
                        'bm' => __('Bambara (bamanankan)', 'modularity'),
                        'ba' => __('Bashkir (башҡорт теле)', 'modularity'),
                        'eu' => __('Basque (euskara, euskera)', 'modularity'),
                        'be' => __('Belarusian (Беларуская)', 'modularity'),
                        'bn' => __('Bengali (বাংলা)', 'modularity'),
                        'bh' => __('Bihari (भोजपुरी)', 'modularity'),
                        'bi' => __('Bislama (Bislama)', 'modularity'),
                        'bs' => __('Bosnian (bosanski jezik)', 'modularity'),
                        'br' => __('Breton (brezhoneg)', 'modularity'),
                        'bg' => __('Bulgarian (български език)', 'modularity'),
                        'my' => __('Burmese (ဗမာစာ)', 'modularity'),
                        'ca' => __('Catalan (Català)', 'modularity'),
                        'ch' => __('Chamorro (Chamoru)', 'modularity'),
                        'ce' => __('Chechen (нохчийн мотт)', 'modularity'),
                        'ny' => __('Chichewa (chiCheŵa, chinyanja)', 'modularity'),
                        'zh' => __('Chinese (中文 (Zhōngwén), 汉语, 漢語)', 'modularity'),
                        'cv' => __('Chuvash (чӑваш чӗлхи)', 'modularity'),
                        'kw' => __('Cornish (Kernewek)', 'modularity'),
                        'co' => __('Corsican (corsu, lingua corsa)', 'modularity'),
                        'cr' => __('Cree (ᓀᐦᐃᔭᐍᐏᐣ)', 'modularity'),
                        'hr' => __('Croatian (hrvatski)', 'modularity'),
                        'cs' => __('Czech (česky, čeština)', 'modularity'),
                        'da' => __('Danish (dansk)', 'modularity'),
                        'dv' => __('Divehi (ދިވެހި)', 'modularity'),
                        'nl' => __('Dutch (Nederlands, Vlaams)', 'modularity'),
                        'en' => __('English (English)', 'modularity'),
                        'eo' => __('Esperanto (Esperanto)', 'modularity'),
                        'et' => __('Estonian (eesti, eesti keel)', 'modularity'),
                        'ee' => __('Ewe (Eʋegbe)', 'modularity'),
                        'fo' => __('Faroese (føroyskt)', 'modularity'),
                        'fj' => __('Fijian (vosa Vakaviti)', 'modularity'),
                        'fi' => __('Finnish (suomi, suomen kieli)', 'modularity'),
                        'fr' => __('French (français, langue française)', 'modularity'),
                        'ff' => __('Fula (Fulfulde, Pulaar, Pular)', 'modularity'),
                        'gl' => __('Galician (Galego)', 'modularity'),
                        'ka' => __('Georgian (ქართული)', 'modularity'),
                        'de' => __('German (Deutsch)', 'modularity'),
                        'el' => __('Greek (Ελληνικά)', 'modularity'),
                        'gn' => __('Guaraní (Avañeẽ)', 'modularity'),
                        'gu' => __('Gujarati (ગુજરાતી)', 'modularity'),
                        'ht' => __('Haitian (Kreyòl ayisyen)', 'modularity'),
                        'ha' => __('Hausa (Hausa, هَوُسَ)', 'modularity'),
                        'he' => __('Hebrew (modern) (עברית)', 'modularity'),
                        'hz' => __('Herero (Otjiherero)', 'modularity'),
                        'hi' => __('Hindi (हिन्दी, हिंदी)', 'modularity'),
                        'ho' => __('Hiri Motu (Hiri Motu)', 'modularity'),
                        'hu' => __('Hungarian (Magyar)', 'modularity'),
                        'ia' => __('Interlingua (Interlingua)', 'modularity'),
                        'id' => __('Indonesian (Bahasa Indonesia)', 'modularity'),
                        'ie' => __('Interlingue (Originally called Occidental; then Interlingue after WWII)', 'modularity'),
                        'ga' => __('Irish (Gaeilge)', 'modularity'),
                        'ig' => __('Igbo (Asụsụ Igbo)', 'modularity'),
                        'ik' => __('Inupiaq (Iñupiaq, Iñupiatun)', 'modularity'),
                        'io' => __('Ido (Ido)', 'modularity'),
                        'is' => __('Icelandic (Íslenska)', 'modularity'),
                        'it' => __('Italian (Italiano)', 'modularity'),
                        'iu' => __('Inuktitut (ᐃᓄᒃᑎᑐᑦ)', 'modularity'),
                        'ja' => __('Japanese (日本語 (にほんご／にっぽんご))', 'modularity'),
                        'jv' => __('Javanese (basa Jawa)', 'modularity'),
                        'kl' => __('Kalaallisut (kalaallisut, kalaallit oqaasii)', 'modularity'),
                        'kn' => __('Kannada (ಕನ್ನಡ)', 'modularity'),
                        'kr' => __('Kanuri (Kanuri)', 'modularity'),
                        'ks' => __('Kashmiri (कश्मीरी, كشميري‎)', 'modularity'),
                        'kk' => __('Kazakh (Қазақ тілі)', 'modularity'),
                        'km' => __('Khmer (ភាសាខ្មែរ)', 'modularity'),
                        'ki' => __('Kikuyu (Gĩkũyũ)', 'modularity'),
                        'rw' => __('Kinyarwanda (Ikinyarwanda)', 'modularity'),
                        'ky' => __('Kirghiz (кыргыз тили)', 'modularity'),
                        'kv' => __('Komi (коми кыв)', 'modularity'),
                        'kg' => __('Kongo (KiKongo)', 'modularity'),
                        'ko' => __('Korean (한국어 (韓國語), 조선말 (朝鮮語))', 'modularity'),
                        'ku' => __('Kurdish (Kurdî, كوردی‎)', 'modularity'),
                        'kj' => __('Kwanyama (Kuanyama)', 'modularity'),
                        'la' => __('Latin (latine, lingua latina)', 'modularity'),
                        'lb' => __('Luxembourgish (Lëtzebuergesch)', 'modularity'),
                        'lg' => __('Luganda (Luganda)', 'modularity'),
                        'li' => __('Limburgish (Limburgs)', 'modularity'),
                        'ln' => __('Lingala (Lingála)', 'modularity'),
                        'lo' => __('Lao (ພາສາລາວ)', 'modularity'),
                        'lt' => __('Lithuanian (lietuvių kalba)', 'modularity'),
                        'lu' => __('Luba-Katanga ()', 'modularity'),
                        'lv' => __('Latvian (latviešu valoda)', 'modularity'),
                        'gv' => __('Manx (Gaelg, Gailck)', 'modularity'),
                        'mk' => __('Macedonian (македонски јазик)', 'modularity'),
                        'mg' => __('Malagasy (Malagasy fiteny)', 'modularity'),
                        'ms' => __('Malay (bahasa Melayu, بهاس ملايو‎)', 'modularity'),
                        'ml' => __('Malayalam (മലയാളം)', 'modularity'),
                        'mt' => __('Maltese (Malti)', 'modularity'),
                        'mi' => __('Māori (te reo Māori)', 'modularity'),
                        'mr' => __('Marathi (Marāṭhī) (मराठी)', 'modularity'),
                        'mh' => __('Marshallese (Kajin M̧ajeļ)', 'modularity'),
                        'mn' => __('Mongolian (монгол)', 'modularity'),
                        'na' => __('Nauru (Ekakairũ Naoero)', 'modularity'),
                        'nv' => __('Navajo (Diné bizaad, Dinékʼehǰí)', 'modularity'),
                        'nb' => __('Norwegian Bokmål (Norsk bokmål)', 'modularity'),
                        'nd' => __('North Ndebele (isiNdebele)', 'modularity'),
                        'ne' => __('Nepali (नेपाली)', 'modularity'),
                        'ng' => __('Ndonga (Owambo)', 'modularity'),
                        'nn' => __('Norwegian Nynorsk (Norsk nynorsk)', 'modularity'),
                        'no' => __('Norwegian (Norsk)', 'modularity'),
                        'ii' => __('Nuosu (ꆈꌠ꒿ Nuosuhxop)', 'modularity'),
                        'nr' => __('South Ndebele (isiNdebele)', 'modularity'),
                        'oc' => __('Occitan (Occitan)', 'modularity'),
                        'oj' => __('Ojibwe (ᐊᓂᔑᓈᐯᒧᐎᓐ)', 'modularity'),
                        'cu' => __('Old Church Slavonic (ѩзыкъ словѣньскъ)', 'modularity'),
                        'om' => __('Oromo (Afaan Oromoo)', 'modularity'),
                        'or' => __('Oriya (ଓଡ଼ିଆ)', 'modularity'),
                        'os' => __('Ossetian (ирон æвзаг)', 'modularity'),
                        'pa' => __('Panjabi (ਪੰਜਾਬੀ, پنجابی‎)', 'modularity'),
                        'pi' => __('Pāli (पाऴि)', 'modularity'),
                        'fa' => __('Persian (فارسی)', 'modularity'),
                        'pl' => __('Polish (polski)', 'modularity'),
                        'ps' => __('Pashto (پښتو)', 'modularity'),
                        'pt' => __('Portuguese (Português)', 'modularity'),
                        'qu' => __('Quechua (Runa Simi, Kichwa)', 'modularity'),
                        'rm' => __('Romansh (rumantsch grischun)', 'modularity'),
                        'rn' => __('Kirundi (kiRundi)', 'modularity'),
                        'ro' => __('Romanian (română)', 'modularity'),
                        'ru' => __('Russian (русский язык)', 'modularity'),
                        'sa' => __('Sanskrit (Saṁskṛta) (संस्कृतम्)', 'modularity'),
                        'sc' => __('Sardinian (sardu)', 'modularity'),
                        'sd' => __('Sindhi (सिन्धी, سنڌي، سندھی‎)', 'modularity'),
                        'se' => __('Northern Sami (Davvisámegiella)', 'modularity'),
                        'sm' => __('Samoan (gagana faa Samoa)', 'modularity'),
                        'sg' => __('Sango (yângâ tî sängö)', 'modularity'),
                        'sr' => __('Serbian (српски језик)', 'modularity'),
                        'gd' => __('Scottish Gaelic (Gàidhlig)', 'modularity'),
                        'sn' => __('Shona (chiShona)', 'modularity'),
                        'si' => __('Sinhala (සිංහල)', 'modularity'),
                        'sk' => __('Slovak (slovenčina)', 'modularity'),
                        'sl' => __('Slovene (slovenščina)', 'modularity'),
                        'so' => __('Somali (Soomaaliga, af Soomaali)', 'modularity'),
                        'st' => __('Southern Sotho (Sesotho)', 'modularity'),
                        'es' => __('Spanish (español, castellano)', 'modularity'),
                        'su' => __('Sundanese (Basa Sunda)', 'modularity'),
                        'sw' => __('Swahili (Kiswahili)', 'modularity'),
                        'ss' => __('Swati (SiSwati)', 'modularity'),
                        'sv' => __('Swedish (svenska)', 'modularity'),
                        'ta' => __('Tamil (தமிழ்)', 'modularity'),
                        'te' => __('Telugu (తెలుగు)', 'modularity'),
                        'tg' => __('Tajik (тоҷикӣ, toğikī, تاجیکی‎)', 'modularity'),
                        'th' => __('Thai (ไทย)', 'modularity'),
                        'ti' => __('Tigrinya (ትግርኛ)', 'modularity'),
                        'bo' => __('Tibetan Standard (བོད་ཡིག)', 'modularity'),
                        'tk' => __('Turkmen (Türkmen, Түркмен)', 'modularity'),
                        'tl' => __('Tagalog (Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔)', 'modularity'),
                        'tn' => __('Tswana (Setswana)', 'modularity'),
                        'to' => __('Tonga (Tonga Islands) (faka Tonga)', 'modularity'),
                        'tr' => __('Turkish (Türkçe)', 'modularity'),
                        'ts' => __('Tsonga (Xitsonga)', 'modularity'),
                        'tt' => __('Tatar (татарча, tatarça, تاتارچا‎)', 'modularity'),
                        'tw' => __('Twi (Twi)', 'modularity'),
                        'ty' => __('Tahitian (Reo Tahiti)', 'modularity'),
                        'ug' => __('Uighur (Uyƣurqə, ئۇيغۇرچە‎)', 'modularity'),
                        'uk' => __('Ukrainian (українська)', 'modularity'),
                        'ur' => __('Urdu (اردو)', 'modularity'),
                        'uz' => __('Uzbek (zbek, Ўзбек, أۇزبېك‎)', 'modularity'),
                        've' => __('Venda (Tshivenḓa)', 'modularity'),
                        'vi' => __('Vietnamese (Tiếng Việt)', 'modularity'),
                        'vo' => __('Volapük (Volapük)', 'modularity'),
                        'wa' => __('Walloon (Walon)', 'modularity'),
                        'cy' => __('Welsh (Cymraeg)', 'modularity'),
                        'wo' => __('Wolof (Wollof)', 'modularity'),
                        'fy' => __('Western Frisian (Frysk)', 'modularity'),
                        'xh' => __('Xhosa (isiXhosa)', 'modularity'),
                        'yi' => __('Yiddish (ייִדיש)', 'modularity'),
                        'yo' => __('Yoruba (Yorùbá)', 'modularity'),
                        'za' => __('Zhuang (Saɯ cueŋƅ, Saw cuengh)', 'modularity'),
                    ),
                    'default_value' => __('sv', 'modularity'),
                    'return_format' => 'array',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_637f27e8eb86c',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-video',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/video',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}