<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_614b3f1a751bf',
        'title' => __('Hero', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_63ca5ed1394e1',
                'label' => __('Display as', 'municipio'),
                'name' => 'mod_hero_display_as',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'default' => __('Default', 'municipio'),
                    'twoColumn' => __('Two columns', 'municipio'),
                    'callToActions' => __('Call to Actions', 'municipio'),
                ],
                'default_value' => __('default', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            1 => [
                'key' => 'field_63ca60c84bb03',
                'label' => __('Background color', 'municipio'),
                'name' => 'mod_hero_background_color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '==',
                            'value' => 'twoColumn',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => __('rgba(255,255,255,0.0)', 'municipio'),
                'enable_opacity' => 1,
                'return_format' => 'string',
            ],
            2 => [
                'key' => 'field_63d7907b6805a',
                'label' => __('Text color', 'municipio'),
                'name' => 'mod_hero_text_color',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '==',
                            'value' => 'twoColumn',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'white' => __('White', 'municipio'),
                    'black' => __('Black', 'municipio'),
                ],
                'default_value' => __('white', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            3 => [
                'key' => 'field_614b3f1e6ed4a',
                'label' => __('Byline', 'municipio'),
                'name' => 'mod_hero_byline',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __('A clear byline, to say something else.', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '!=',
                            'value' => 'callToActions',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            4 => [
                'key' => 'field_63d78c4897632',
                'label' => __('Meta', 'municipio'),
                'name' => 'mod_hero_meta',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '!=',
                            'value' => 'callToActions',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            5 => [
                'key' => 'field_614b3f5a6ed4b',
                'label' => __('Body', 'municipio'),
                'name' => 'mod_hero_body',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => __(
                    'A short and concise text about this site. What\'s it about? Maximum 500 characters.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'render_type' => '',
                'filter_context' => '',
                'share_option' => 0,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => 500,
                'rows' => 4,
                'new_lines' => '',
                'wp_object' => '',
                'acfe_textarea_code' => 0,
            ],
            6 => [
                'key' => 'field_62c3f89f983b1',
                'label' => __('Background type', 'municipio'),
                'name' => 'mod_hero_background_type',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'image' => __('Image', 'municipio'),
                    'video' => __('Video', 'municipio'),
                ],
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            7 => [
                'key' => 'field_614b3f786ed4c',
                'label' => __('Background image', 'municipio'),
                'name' => 'mod_hero_background_image',
                'aria-label' => '',
                'type' => 'focuspoint',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_62c3f89f983b1',
                            'operator' => '==',
                            'value' => 'image',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'preview_size' => 'large',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
            ],
            8 => [
                'key' => 'field_62c3f8fa57719',
                'label' => __('Background video', 'municipio'),
                'name' => 'mod_hero_background_video',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_62c3f89f983b1',
                            'operator' => '==',
                            'value' => 'video',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'mp4',
                'uploader' => '',
            ],
            9 => [
                'key' => 'field_646f25456ea80',
                'label' => __('Poster image', 'municipio'),
                'name' => 'mod_hero_poster_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_62c3f89f983b1',
                            'operator' => '==',
                            'value' => 'video',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'uploader' => '',
                'acfe_thumbnail' => 0,
                'return_format' => 'array',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            10 => [
                'key' => 'field_684bf60873e57',
                'label' => __('Display media above content', 'municipio'),
                'name' => 'mod_hero_media_first',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '==',
                            'value' => 'callToActions',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            11 => [
                'key' => 'field_614b43a186da4',
                'label' => __('Size', 'municipio'),
                'name' => 'mod_hero_size',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'small' => __('Small', 'municipio'),
                    'normal' => __('Normal', 'municipio'),
                    'large' => __('Large', 'municipio'),
                ],
                'default_value' => __('normal', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            12 => [
                'key' => 'field_6848393a785be',
                'label' => __('Buttons', 'municipio'),
                'name' => 'mod_hero_buttons',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_63ca5ed1394e1',
                            'operator' => '==',
                            'value' => 'callToActions',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 1,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __('Add Call to Action button', 'municipio'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_6848395c785bf',
                        'label' => __('Link', 'municipio'),
                        'name' => 'link',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'parent_repeater' => 'field_6848393a785be',
                    ],
                    1 => [
                        'key' => 'field_68483977785c0',
                        'label' => __('Type', 'municipio'),
                        'name' => 'type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'basic' => __('Basic', 'municipio'),
                            'filled' => __('Filled', 'municipio'),
                            'outlined' => __('Outlined', 'municipio'),
                        ],
                        'default_value' => __('filled', 'municipio'),
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'parent_repeater' => 'field_6848393a785be',
                    ],
                    2 => [
                        'key' => 'field_68483b78fe5b6',
                        'label' => __('Color', 'municipio'),
                        'name' => 'color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [
                            'default' => __('Default', 'municipio'),
                            'primary' => __('Primary', 'municipio'),
                            'secondary' => __('Secondary', 'municipio'),
                        ],
                        'default_value' => __('primary', 'municipio'),
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'parent_repeater' => 'field_6848393a785be',
                    ],
                ],
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-hero',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/hero',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
