<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_636e424039120',
    'title' => __('Screen reader language', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_636e42408367e',
            'label' => __('Language', 'modularity'),
            'name' => 'lang',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('For accessibility reasons; what language should this this content be parsed as when read aloud by a screen reader?', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'auto' => __('Auto detected language', 'modularity'),
                'af' => __('Afrikaans', 'modularity'),
                'sq' => __('Albanian', 'modularity'),
                'ar-dz' => __('Arabic (Algeria)', 'modularity'),
                'ar-bh' => __('Arabic (Bahrain)', 'modularity'),
                'ar-eg' => __('Arabic (Egypt)', 'modularity'),
                'ar-iq' => __('Arabic (Iraq)', 'modularity'),
                'ar-jo' => __('Arabic (Jordan)', 'modularity'),
                'ar-kw' => __('Arabic (Kuwait)', 'modularity'),
                'ar-lb' => __('Arabic (Lebanon)', 'modularity'),
                'ar-ly' => __('Arabic (Libya)', 'modularity'),
                'ar-ma' => __('Arabic (Morocco)', 'modularity'),
                'ar-om' => __('Arabic (Oman)', 'modularity'),
                'ar-qa' => __('Arabic (Qatar)', 'modularity'),
                'ar-sa' => __('Arabic (Saudi Arabia)', 'modularity'),
                'ar-sy' => __('Arabic (Syria)', 'modularity'),
                'ar-tn' => __('Arabic (Tunisia)', 'modularity'),
                'ar-ae' => __('Arabic (U.A.E.)', 'modularity'),
                'ar-ye' => __('Arabic (Yemen)', 'modularity'),
                'eu' => __('Basque', 'modularity'),
                'be' => __('Belarusian', 'modularity'),
                'bg' => __('Bulgarian', 'modularity'),
                'ca' => __('Catalan', 'modularity'),
                'zh-hk' => __('Chinese (Hong Kong)', 'modularity'),
                'zh-cn' => __('Chinese (PRC)', 'modularity'),
                'zh-sg' => __('Chinese (Singapore)', 'modularity'),
                'zh-tw' => __('Chinese (Taiwan)', 'modularity'),
                'hr' => __('Croatian', 'modularity'),
                'cs' => __('Czech', 'modularity'),
                'da' => __('Danish', 'modularity'),
                'nl-be' => __('Dutch (Belgium)', 'modularity'),
                'nl' => __('Dutch (Standard)', 'modularity'),
                'en' => __('English', 'modularity'),
                'en-au' => __('English (Australia)', 'modularity'),
                'en-bz' => __('English (Belize)', 'modularity'),
                'en-ca' => __('English (Canada)', 'modularity'),
                'en-ie' => __('English (Ireland)', 'modularity'),
                'en-jm' => __('English (Jamaica)', 'modularity'),
                'en-nz' => __('English (New Zealand)', 'modularity'),
                'en-za' => __('English (South Africa)', 'modularity'),
                'en-tt' => __('English (Trinidad)', 'modularity'),
                'en-gb' => __('English (United Kingdom)', 'modularity'),
                'en-us' => __('English (United States)', 'modularity'),
                'et' => __('Estonian', 'modularity'),
                'fo' => __('Faeroese', 'modularity'),
                'fa' => __('Farsi', 'modularity'),
                'fi' => __('Finnish', 'modularity'),
                'fr-be' => __('French (Belgium)', 'modularity'),
                'fr-ca' => __('French (Canada)', 'modularity'),
                'fr-lu' => __('French (Luxembourg)', 'modularity'),
                'fr' => __('French (Standard)', 'modularity'),
                'fr-ch' => __('French (Switzerland)', 'modularity'),
                'gd' => __('Gaelic (Scotland)', 'modularity'),
                'de-at' => __('German (Austria)', 'modularity'),
                'de-li' => __('German (Liechtenstein)', 'modularity'),
                'de-lu' => __('German (Luxembourg)', 'modularity'),
                'de' => __('German (Standard)', 'modularity'),
                'de-ch' => __('German (Switzerland)', 'modularity'),
                'el' => __('Greek', 'modularity'),
                'he' => __('Hebrew', 'modularity'),
                'hi' => __('Hindi', 'modularity'),
                'hu' => __('Hungarian', 'modularity'),
                'is' => __('Icelandic', 'modularity'),
                'id' => __('Indonesian', 'modularity'),
                'ga' => __('Irish', 'modularity'),
                'it' => __('Italian (Standard)', 'modularity'),
                'it-ch' => __('Italian (Switzerland)', 'modularity'),
                'ja' => __('Japanese', 'modularity'),
                'ko' => __('Korean (Johab)', 'modularity'),
                'ku' => __('Kurdish', 'modularity'),
                'lv' => __('Latvian', 'modularity'),
                'lt' => __('Lithuanian', 'modularity'),
                'mk' => __('Macedonian (FYROM)', 'modularity'),
                'ml' => __('Malayalam', 'modularity'),
                'ms' => __('Malaysian', 'modularity'),
                'mt' => __('Maltese', 'modularity'),
                'no' => __('Norwegian', 'modularity'),
                'nb' => __('Norwegian (Bokmål)', 'modularity'),
                'nn' => __('Norwegian (Nynorsk)', 'modularity'),
                'pl' => __('Polish', 'modularity'),
                'pt-br' => __('Portuguese (Brazil)', 'modularity'),
                'pt' => __('Portuguese (Portugal)', 'modularity'),
                'pa' => __('Punjabi', 'modularity'),
                'rm' => __('Rhaeto-Romanic', 'modularity'),
                'ro' => __('Romanian', 'modularity'),
                'ro-md' => __('Romanian (Republic of Moldova)', 'modularity'),
                'ru' => __('Russian', 'modularity'),
                'ru-md' => __('Russian (Republic of Moldova)', 'modularity'),
                'sr' => __('Serbian', 'modularity'),
                'sk' => __('Slovak', 'modularity'),
                'sl' => __('Slovenian', 'modularity'),
                'sb' => __('Sorbian', 'modularity'),
                'es-ar' => __('Spanish (Argentina)', 'modularity'),
                'es-bo' => __('Spanish (Bolivia)', 'modularity'),
                'es-cl' => __('Spanish (Chile)', 'modularity'),
                'es-co' => __('Spanish (Colombia)', 'modularity'),
                'es-cr' => __('Spanish (Costa Rica)', 'modularity'),
                'es-do' => __('Spanish (Dominican Republic)', 'modularity'),
                'es-ec' => __('Spanish (Ecuador)', 'modularity'),
                'es-sv' => __('Spanish (El Salvador)', 'modularity'),
                'es-gt' => __('Spanish (Guatemala)', 'modularity'),
                'es-hn' => __('Spanish (Honduras)', 'modularity'),
                'es-mx' => __('Spanish (Mexico)', 'modularity'),
                'es-ni' => __('Spanish (Nicaragua)', 'modularity'),
                'es-pa' => __('Spanish (Panama)', 'modularity'),
                'es-py' => __('Spanish (Paraguay)', 'modularity'),
                'es-pe' => __('Spanish (Peru)', 'modularity'),
                'es-pr' => __('Spanish (Puerto Rico)', 'modularity'),
                'es' => __('Spanish (Spain)', 'modularity'),
                'es-uy' => __('Spanish (Uruguay)', 'modularity'),
                'es-ve' => __('Spanish (Venezuela)', 'modularity'),
                'sv-se' => __('Swedish', 'modularity'),
                'sv-fi' => __('Swedish (Finland)', 'modularity'),
                'th' => __('Thai', 'modularity'),
                'ts' => __('Tsonga', 'modularity'),
                'tn' => __('Tswana', 'modularity'),
                'tr' => __('Turkish', 'modularity'),
                'ua' => __('Ukrainian', 'modularity'),
                'ur' => __('Urdu', 'modularity'),
                've' => __('Venda', 'modularity'),
                'vi' => __('Vietnamese', 'modularity'),
                'cy' => __('Welsh', 'modularity'),
                'xh' => __('Xhosa', 'modularity'),
                'ji' => __('Yiddish', 'modularity'),
                'zu' => __('Zulu', 'modularity'),
            ),
            'default_value' => __('auto', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'search_placeholder' => '',
            'allow_null' => 0,
            'ui' => 1,
            'ajax' => 0,
            'placeholder' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'all',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'all',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}