<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_66c34c64b8d10',
    'title' => __('Menu Module', 'municipio'),
    'fields' => array(
        0 => array(
            'key' => 'field_66c59ae797a04',
            'label' => __('Display Menu As', 'municipio'),
            'name' => 'mod_menu_display_as',
            'aria-label' => '',
            'type' => 'image_select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'row-row-row-row-row-row-row-66c59af297a05' => array(
                    'image-select-repeater-label' => 'List',
                    'image-select-repeater-value' => 'listing',
                ),
            ),
        ),
        1 => array(
            'key' => 'field_66c5c58856a24',
            'label' => __('Display as conditional target', 'municipio'),
            'name' => 'mod_menu_display_as_conditional',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'acf-hidden',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        2 => array(
            'key' => 'field_66c34c655680e',
            'label' => __('Select a Menu', 'municipio'),
            'name' => 'mod_menu_menu',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                119019 => __('Arbete - Lediga jobb', 'municipio'),
                329913 => __('Drömljus - meny', 'municipio'),
                119214 => __('E-Tjänster', 'municipio'),
                329389 => __('Företagare', 'municipio'),
                329425 => __('Företagare_landningssida', 'municipio'),
                239963 => __('Förskolor', 'municipio'),
                239955 => __('Grundskolor', 'municipio'),
                118901 => __('Huvudmeny', 'municipio'),
                330371 => __('Kommun och politik test', 'municipio'),
                119453 => __('Kundtyp', 'municipio'),
                329060 => __('Meny i modul på startsida', 'municipio'),
                329061 => __('Menymodul', 'municipio'),
                119454 => __('Mina Sidor Meny', 'municipio'),
                119482 => __('Mobilmeny', 'municipio'),
                119483 => __('Mobilmenyy nedre', 'municipio'),
                330372 => __('Samhällsservice', 'municipio'),
                5 => __('Sidfotsmeny', 'municipio'),
                119295 => __('Språkväljare', 'municipio'),
                329426 => __('Starta-driva-företag', 'municipio'),
                330433 => __('Test', 'municipio'),
                3 => __('visionsfonden', 'municipio'),
                329388 => __('Våra webbplatser', 'municipio'),
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
        3 => array(
            'key' => 'field_6734a0413d66b',
            'label' => __('Background', 'municipio'),
            'name' => 'mod_menu_wrapped',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Decides if the menu is wrapped in a container.', 'municipio'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        4 => array(
            'key' => 'field_6ab25d8ae29a0',
            'label' => __('Spacing', 'municipio'),
            'name' => 'mod_menu_spaced',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('This adds spacing between the items. Making them all appear as separate cards instead of one big card.', 'municipio'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6734a0413d66b',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        5 => array(
            'key' => 'field_67c846a5654c1',
            'label' => __('Collapse menu on mobile', 'municipio'),
            'name' => 'mod_menu_mobile_collapse',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Will collapse menu groups on mobile to save vertical space. User has ability to expand individual menu groups with a button click.', 'municipio'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'allow_in_bindings' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-menu',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/menu',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
));
}