<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_5729f4d3e7c7a',
        'title' => __('Wordpress Widget', 'municipio'),
        'fields' => [
            0 => [
                'layout' => 'horizontal',
                'choices' => [
                    'WP_Widget_Archives' => __('Arkiv', 'municipio'),
                    'WP_Widget_Calendar' => __('Kalender', 'municipio'),
                    'WP_Widget_Categories' => __('Kategorier', 'municipio'),
                    'WP_Widget_Meta' => __('Meta', 'municipio'),
                    'WP_Widget_Pages' => __('Sidor', 'municipio'),
                    'WP_Widget_Recent_Comments' => __('Senaste kommentarerna', 'municipio'),
                    'WP_Widget_Recent_Posts' => __('Senaste inläggen', 'municipio'),
                    'WP_Widget_RSS' => __('RSS', 'municipio'),
                    'WP_Widget_Search' => __('Sök', 'municipio'),
                    'WP_Widget_Tag_Cloud' => __('Taggmoln', 'municipio'),
                ],
                'default_value' => '',
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_572a06dd9d06c',
                'label' => __('Widget Type', 'municipio'),
                'name' => 'mod_standard_widget_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            1 => [
                'message' => __(
                    'There are no options available for this widget type.<br> <style>.acf-field-57309aa0b176d {background-color: #FFDFDF;}</style>',
                    'municipio',
                ),
                'esc_html' => 0,
                'new_lines' => '',
                'key' => 'field_57309aa0b176d',
                'label' => __('No options avabile', 'municipio'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Calendar',
                        ],
                    ],
                    1 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Meta',
                        ],
                    ],
                    2 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Search',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            2 => [
                'layout' => 'horizontal',
                'choices' => [
                    0 => __('No', 'municipio'),
                    1 => __('Yes', 'municipio'),
                ],
                'default_value' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_5730a1f85e023',
                'label' => __('Show number of items indicator', 'municipio'),
                'name' => 'wp_widget_archive_count',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Archives',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
            ],
            3 => [
                'layout' => 'horizontal',
                'choices' => [
                    0 => __('No', 'municipio'),
                    1 => __('Yes', 'municipio'),
                ],
                'default_value' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_57319d35a5915',
                'label' => __('Show as dropdown list', 'municipio'),
                'name' => 'wp_widget_archive_dropdown',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Archives',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
            ],
            4 => [
                'layout' => 'horizontal',
                'choices' => [
                    0 => __('No', 'municipio'),
                    1 => __('Yes', 'municipio'),
                ],
                'default_value' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_57319e7e4900e',
                'label' => __('Show number of category items indicator', 'municipio'),
                'name' => 'wp_widget_cat_count',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Categories',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '33,333',
                    'class' => '',
                    'id' => '',
                ],
            ],
            5 => [
                'layout' => 'horizontal',
                'choices' => [
                    0 => __('No', 'municipio'),
                    1 => __('Yes', 'municipio'),
                ],
                'default_value' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_5731aa7f0f0f8',
                'label' => __('Show as hierarchial list', 'municipio'),
                'name' => 'wp_widget_cat_hierarchical',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Categories',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '33,333',
                    'class' => '',
                    'id' => '',
                ],
            ],
            6 => [
                'layout' => 'horizontal',
                'choices' => [
                    0 => __('No', 'municipio'),
                    1 => __('Yes', 'municipio'),
                ],
                'default_value' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
                'key' => 'field_5731aaac9c7d2',
                'label' => __('Show as dropdown', 'municipio'),
                'name' => 'wp_widget_cat_dropdown',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Categories',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '33,333',
                    'class' => '',
                    'id' => '',
                ],
            ],
            7 => [
                'multiple' => 0,
                'allow_null' => 0,
                'choices' => [
                    'post_title' => __('Titel', 'municipio'),
                    'menu_order' => __('Menu order', 'municipio'),
                    'ID' => __('Page ID', 'municipio'),
                ],
                'default_value' => [],
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'key' => 'field_5731e69671076',
                'label' => __('Sort by', 'municipio'),
                'name' => 'wp_widget_pages_sort_by',
                'type' => 'select',
                'instructions' => __('Select how to sort the pages', 'municipio'),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Pages',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
                'disabled' => 0,
                'readonly' => 0,
            ],
            8 => [
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5731e78c71077',
                'label' => __('Exclude', 'municipio'),
                'name' => 'wp_widget_pages_exclude',
                'type' => 'text',
                'instructions' => __('ID:s of pages to exclude. Separated by comma.', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Pages',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
                'readonly' => 0,
                'disabled' => 0,
            ],
            9 => [
                'default_value' => 5,
                'min' => 1,
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5731e8cf25b42',
                'label' => __('Number of comments to show', 'municipio'),
                'name' => 'wp_widget_comments_comments',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Recent_Comments',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'readonly' => 0,
                'disabled' => 0,
            ],
            10 => [
                'default_value' => 5,
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5731e9c32cd95',
                'label' => __('Number of posts to show', 'municipio'),
                'name' => 'wp_widget_posts_number',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Recent_Posts',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'readonly' => 0,
                'disabled' => 0,
            ],
            11 => [
                'default_value' => '',
                'placeholder' => '',
                'key' => 'field_5731ea87eae83',
                'label' => __('RSS Url', 'municipio'),
                'name' => 'wp_widget_rss_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_RSS',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            12 => [
                'default_value' => 5,
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_5731ea9beae84',
                'label' => __('Items to show', 'municipio'),
                'name' => 'wp_widget_rss_items',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_RSS',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 25,
                    'class' => '',
                    'id' => '',
                ],
                'readonly' => 0,
                'disabled' => 0,
            ],
            13 => [
                'default_value' => 0,
                'message' => __('Yes, show summary', 'municipio'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5731eab4eae85',
                'label' => __('Show summary', 'municipio'),
                'name' => 'wp_widget_rss_summary',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_RSS',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 25,
                    'class' => '',
                    'id' => '',
                ],
            ],
            14 => [
                'default_value' => 0,
                'message' => __('Yes, show author', 'municipio'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5731eaceeae86',
                'label' => __('Visa författare', 'municipio'),
                'name' => 'wp_widget_rss_author',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_RSS',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 25,
                    'class' => '',
                    'id' => '',
                ],
            ],
            15 => [
                'default_value' => 0,
                'message' => __('Yes, show date', 'municipio'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5731eae5eae87',
                'label' => __('Show date', 'municipio'),
                'name' => 'wp_widget_rss_date',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_RSS',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 25,
                    'class' => '',
                    'id' => '',
                ],
            ],
            16 => [
                'multiple' => 0,
                'allow_null' => 0,
                'choices' => [
                    'category' => __('Kategorier', 'municipio'),
                    'post_tag' => __('Taggar', 'municipio'),
                    'link_category' => __('Länkkategorier', 'municipio'),
                    'listing-category' => __('Kategori', 'municipio'),
                    'listing-places' => __('Plats', 'municipio'),
                    'amne' => __('Ämne', 'municipio'),
                ],
                'default_value' => [],
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'return_format' => 'value',
                'key' => 'field_5731ebd018370',
                'label' => __('Taxonomy', 'municipio'),
                'name' => 'wp_widget_tag_cloud_taxonomy',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_572a06dd9d06c',
                            'operator' => '==',
                            'value' => 'WP_Widget_Tag_Cloud',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'disabled' => 0,
                'readonly' => 0,
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-wpwidget',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            14 => 'send-trackbacks',
        ],
        'active' => 1,
        'description' => '',
        'modified' => 1462889442,
        'local' => 'php',
    ]);
}
