<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_64a29154aa972',
    'title' => __('Modal', 'municipio'),
    'fields' => array(
        0 => array(
            'key' => 'field_64a2b8ad7c9cf',
            'label' => __('Button', 'municipio'),
            'name' => 'button',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 1,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_64a2b8c37c9d0',
                    'label' => __('Text', 'municipio'),
                    'name' => 'text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                1 => array(
                    'key' => 'field_64a2b8dd7c9d1',
                    'label' => __('Icon', 'municipio'),
                    'name' => 'material_icon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'allow_in_bindings' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),
                2 => array(
                    'key' => 'field_64a3d199a731c',
                    'label' => __('Icon position', 'municipio'),
                    'name' => 'reverse_position',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        1 => __('Left of text', 'municipio'),
                        0 => __('Right of text', 'municipio'),
                    ),
                    'default_value' => 1,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                3 => array(
                    'key' => 'field_64a3d09ba7318',
                    'label' => __('Style', 'municipio'),
                    'name' => 'style',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'basic' => __('Basic', 'municipio'),
                        'filled' => __('Filled', 'municipio'),
                        'outlined' => __('Outlined', 'municipio'),
                    ),
                    'default_value' => __('filled', 'municipio'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                4 => array(
                    'key' => 'field_64a3d14da731b',
                    'label' => __('Color scheme', 'municipio'),
                    'name' => 'color',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'primary' => __('Primary', 'municipio'),
                        'secondary' => __('Secondary', 'municipio'),
                        'default' => __('Default', 'municipio'),
                    ),
                    'default_value' => __('primary', 'municipio'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                5 => array(
                    'key' => 'field_64a3d10aa731a',
                    'label' => __('Size', 'municipio'),
                    'name' => 'size',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'sm' => __('Small', 'municipio'),
                        'md' => __('Medium', 'municipio'),
                        'lg' => __('Large', 'municipio'),
                    ),
                    'default_value' => __('lg', 'municipio'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
            ),
        ),
        1 => array(
            'key' => 'field_64a3ab6b5abaf',
            'label' => __('Modal', 'municipio'),
            'name' => 'modal',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_64a29155e2129',
                    'label' => __('Modal Content', 'municipio'),
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'modal-content',
                    ),
                    'post_status' => array(
                        0 => 'publish',
                    ),
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 0,
                    'save_custom' => 0,
                    'save_post_status' => 'publish',
                    'acfe_bidirectional' => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                    'save_post_type' => '',
                ),
                1 => array(
                    'key' => 'field_64a3b31dc4c63',
                    'label' => __('Modal layout settings (Click to expand)', 'municipio'),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'accordion',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'open' => 0,
                    'multi_expand' => 0,
                    'endpoint' => 0,
                ),
                2 => array(
                    'key' => 'field_64a3af018aa15',
                    'label' => __('Use Modal Content title', 'municipio'),
                    'name' => 'use_modal_content_title',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => __('Use the title of the Modal Content post as the heading for this modal.', 'municipio'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
                3 => array(
                    'key' => 'field_64a3abf5237f1',
                    'label' => __('Show as panel', 'municipio'),
                    'name' => 'is_panel',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => __('Enable a panel layout that cover the whole page when opened.', 'municipio'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
                4 => array(
                    'key' => 'field_64a3abacfbf14',
                    'label' => __('Modal Size', 'municipio'),
                    'name' => 'size',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('Empty as default is set to max width 800px.', 'municipio'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_64a3abf5237f1',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'sm' => __('Small', 'municipio'),
                        'md' => __('Medium', 'municipio'),
                        'lg' => __('Large', 'municipio'),
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'placeholder' => __('Select size', 'municipio'),
                    'search_placeholder' => '',
                    'allow_null' => 1,
                    'ui' => 1,
                    'ajax' => 0,
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                5 => array(
                    'key' => 'field_64a3b17c98849',
                    'label' => __('Padding', 'municipio'),
                    'name' => 'padding',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_64a3abf5237f1',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        2 => __('Small', 'municipio'),
                        3 => __('Medium', 'municipio'),
                        4 => __('Large', 'municipio'),
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                6 => array(
                    'key' => 'field_64a3b1cea60e8',
                    'label' => __('Rounded borders', 'municipio'),
                    'name' => 'border_radius',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_64a3abf5237f1',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'sm' => __('Small', 'municipio'),
                        'md' => __('Medium', 'municipio'),
                        'lg' => __('Large', 'municipio'),
                    ),
                    'default_value' => __('md', 'municipio'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-modal',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/modal',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}