<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_64ff22b117e2c',
        'title' => __('Manual Input Data', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_64ff23d0d91bf',
                'label' => __('Display as', 'municipio'),
                'name' => 'display_as',
                'aria-label' => '',
                'type' => 'image_select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'row-row-row-row-row-row-row-row-row-row-651d5ccf5ac81' => [
                        'image-select-repeater-label' => 'Accordion',
                        'image-select-repeater-value' => 'accordion',
                    ],
                    'row-row-row-row-row-row-row-row-row-row-651d5cdb5ac82' => [
                        'image-select-repeater-label' => 'Block',
                        'image-select-repeater-value' => 'block',
                    ],
                    'row-row-row-row-row-row-row-row-row-row-651d5cdf5ac83' => [
                        'image-select-repeater-label' => 'Box',
                        'image-select-repeater-value' => 'box',
                    ],
                    'row-row-row-row-row-row-row-row-row-row-651d5ce55ac84' => [
                        'image-select-repeater-label' => 'Card',
                        'image-select-repeater-value' => 'card',
                    ],
                    'row-row-row-row-row-row-row-row-row-row-651d5ceb5ac85' => [
                        'image-select-repeater-label' => 'Collection',
                        'image-select-repeater-value' => 'collection',
                    ],
                    'row-row-row-row-row-row-row-row-row-row-651d5cf65ac86' => [
                        'image-select-repeater-label' => 'List',
                        'image-select-repeater-value' => 'list',
                    ],
                    'row-row-row-row-row-row-651ffdc788395' => [
                        'image-select-repeater-label' => 'Segment',
                        'image-select-repeater-value' => 'segment',
                    ],
                    '6757ee687d940' => [
                        'image-select-repeater-label' => 'News',
                        'image-select-repeater-value' => 'news',
                    ],
                ],
            ],
            1 => [
                'key' => 'field_6752f959acfda',
                'label' => __('display_as_conditional', 'municipio'),
                'name' => 'display_as_conditional',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => 'acf-hidden',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            2 => [
                'key' => 'field_67126c170c176',
                'label' => __('Allow logged in users to modify their list', 'municipio'),
                'name' => 'allow_user_modification',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            3 => [
                'key' => 'field_678784f60a1a6',
                'label' => __('Save as custom meta key', 'municipio'),
                'name' => 'save_as_custom_meta_key',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __(
                    'Will default to the module ID but can be set to save as a custom meta key.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_67126c170c176',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '70',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => __('unique-key', 'municipio'),
                'prepend' => '',
                'append' => '',
            ],
            4 => [
                'key' => 'field_67289fa6dfea3',
                'label' => __('Free text filtering', 'municipio'),
                'name' => 'free_text_filtering',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Enables filtering using a input field.', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'accordion',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            5 => [
                'key' => 'field_67f66637f8734',
                'label' => __('Spaced sections', 'municipio'),
                'name' => 'accordion_spaced_sections',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Accordion items will have some space between them', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'accordion',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            6 => [
                'key' => 'field_650067ed6cc3c',
                'label' => __('Column marking', 'municipio'),
                'name' => 'accordion_column_marking',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'accordion',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            7 => [
                'key' => 'field_65005968bbc75',
                'label' => __('Column titles', 'municipio'),
                'name' => 'accordion_column_titles',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'accordion',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 4,
                'collapsed' => '',
                'button_label' => __('Lägg till rad', 'municipio'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_65005a33bbc77',
                        'label' => __('Column title', 'municipio'),
                        'name' => 'accordion_column_title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_65005968bbc75',
                    ],
                ],
            ],
            8 => [
                'key' => 'field_65001d039d4c4',
                'label' => __('Columns', 'municipio'),
                'name' => 'columns',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '!=',
                            'value' => 'accordion',
                        ],
                        1 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '!=',
                            'value' => 'list',
                        ],
                        2 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '!=',
                            'value' => 'listing',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'o-grid-12' => __('1', 'municipio'),
                    'o-grid-6' => __('2', 'municipio'),
                    'o-grid-4' => __('3', 'municipio'),
                    'o-grid-3' => __('4', 'municipio'),
                ],
                'default_value' => __('o-grid-4', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            9 => [
                'key' => 'field_663372f4922a5',
                'label' => __('Highlight first input', 'municipio'),
                'name' => 'highlight_first_input',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Makes the first input bigger', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'card',
                        ],
                    ],
                    1 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'segment',
                        ],
                    ],
                    2 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'block',
                        ],
                    ],
                    3 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'news',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            10 => [
                'key' => 'field_68975344a0707',
                'label' => __('Show title above image', 'municipio'),
                'name' => 'title_above_image',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Show title above the card image instead of grouped with text', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'card',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            11 => [
                'key' => 'field_689751b4887b6',
                'label' => __('Disable card layout shift', 'municipio'),
                'name' => 'disable_resize_layout_shift',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Disable the standard card layout shift when browser resizes', 'municipio'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'card',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            12 => [
                'key' => 'field_6641de045ab9d',
                'label' => __('Image position', 'municipio'),
                'name' => 'image_position',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'segment',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    1 => __('left', 'municipio'),
                    0 => __('right', 'municipio'),
                ],
                'default_value' => 1,
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'horizontal',
                'save_other_choice' => 0,
            ],
            13 => [
                'key' => 'field_65016a6f0a085',
                'label' => __('Ratio', 'municipio'),
                'name' => 'ratio',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'block',
                        ],
                    ],
                    1 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'box',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    '1:1' => __('1:1', 'municipio'),
                    '4:3' => __('4:3', 'municipio'),
                    '12:16' => __('12:16', 'municipio'),
                ],
                'default_value' => __('4:3', 'municipio'),
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ],
            14 => [
                'key' => 'field_689b2ce333d43',
                'label' => __('Use custom card color', 'municipio'),
                'name' => 'use_custom_card_color',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_6752f959acfda',
                            'operator' => '==',
                            'value' => 'card',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            15 => [
                'key' => 'field_64ff22b2d91b7',
                'label' => __('Manual inputs', 'municipio'),
                'name' => 'manual_inputs',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __('Lägg till rad', 'municipio'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_64ff22fdd91b8',
                        'label' => __('Title', 'municipio'),
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    1 => [
                        'key' => 'field_64ff2372d91bc',
                        'label' => __('Column values', 'municipio'),
                        'name' => 'accordion_column_values',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'accordion',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'acfe_repeater_stylised_button' => 0,
                        'layout' => 'table',
                        'min' => 0,
                        'max' => 4,
                        'collapsed' => '',
                        'button_label' => __('Lägg till rad', 'municipio'),
                        'rows_per_page' => 20,
                        'parent_repeater' => 'field_64ff22b2d91b7',
                        'sub_fields' => [
                            0 => [
                                'key' => 'field_64ff23afd91bd',
                                'label' => __('Column value', 'municipio'),
                                'name' => 'value',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_64ff2372d91bc',
                            ],
                        ],
                    ],
                    2 => [
                        'key' => 'field_64ff231ed91b9',
                        'label' => __('Content', 'municipio'),
                        'name' => 'content',
                        'aria-label' => '',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '!=',
                                    'value' => 'list',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    3 => [
                        'key' => 'field_64ff232ad91ba',
                        'label' => __('Link', 'municipio'),
                        'name' => 'link',
                        'aria-label' => '',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '!=',
                                    'value' => 'accordion',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    4 => [
                        'key' => 'field_6715fa26bb1ef',
                        'label' => __('Obligatory', 'municipio'),
                        'name' => 'obligatory',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_67126c170c176',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    5 => [
                        'key' => 'field_6718c31e2862b',
                        'label' => __('UniqueId', 'municipio'),
                        'name' => 'unique_id',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_67126c170c176',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    6 => [
                        'key' => 'field_6717a0079988c',
                        'label' => __('Link description', 'municipio'),
                        'name' => 'link_description',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_67126c170c176',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    7 => [
                        'key' => 'field_65002bce6d459',
                        'label' => __('Link text', 'municipio'),
                        'name' => 'link_text',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'segment',
                                ],
                            ],
                            1 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'card',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    8 => [
                        'key' => 'field_64ff2355d91bb',
                        'label' => __('Image', 'municipio'),
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '!=',
                                    'value' => 'list',
                                ],
                                1 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '!=',
                                    'value' => 'accordion',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'uploader' => '',
                        'return_format' => 'id',
                        'acfe_thumbnail' => 0,
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    9 => [
                        'key' => 'field_65293de2a26c7',
                        'label' => __('Icon', 'municipio'),
                        'name' => 'box_icon',
                        'aria-label' => '',
                        'type' => 'icon',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'box',
                                ],
                            ],
                            1 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'list',
                                ],
                            ],
                            2 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'card',
                                ],
                            ],
                            3 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'block',
                                ],
                            ],
                            4 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'segment',
                                ],
                            ],
                            5 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'collection',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                    10 => [
                        'key' => 'field_689b2cf733d44',
                        'label' => __('Custom background color', 'municipio'),
                        'name' => 'custom_background_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => __(
                            'Colors can be defined in site customizer under General appearance > Colors > Additional colors.',
                            'municipio',
                        ),
                        'required' => 1,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_6752f959acfda',
                                    'operator' => '==',
                                    'value' => 'card',
                                ],
                                1 => [
                                    'field' => 'field_689b2ce333d43',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'choices' => [],
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'allow_null' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_64ff22b2d91b7',
                    ],
                ],
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-manualinput',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/manualinput',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => [
            0 => 'json',
        ],
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
