<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_5666a2a71d806',
        'title' => __('Table Editor', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_5731982808842',
                'label' => __('Datatyp', 'municipio'),
                'name' => 'mod_table_data_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'horizontal',
                'choices' => [
                    'manual' => __('Manual input', 'municipio'),
                    'csv' => __('CSV Import', 'municipio'),
                ],
                'default_value' => '',
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
            ],
            1 => [
                'key' => 'field_57319c3b08843',
                'label' => __('CSV-fil', 'municipio'),
                'name' => 'mod_table_csv_file',
                'type' => 'file',
                'instructions' => __('CSV-formatterad fil', 'municipio'),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_5731982808842',
                            'operator' => '==',
                            'value' => 'csv',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '.csv',
            ],
            2 => [
                'key' => 'field_5731a138b52aa',
                'label' => __('CSV-avgränsare', 'municipio'),
                'name' => 'mod_table_csv_delimiter',
                'type' => 'text',
                'instructions' => __(
                    'Tecken som används i CSV-filen som avgränsare. Brukar vara kommatecken eller semikolon.',
                    'municipio',
                ),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_5731982808842',
                            'operator' => '==',
                            'value' => 'csv',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => ';',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],
            3 => [
                'key' => 'field_5666a2ae23643',
                'label' => __('Table', 'municipio'),
                'name' => 'mod_table',
                'type' => 'dynamic_table',
                'instructions' => __(
                    'Enter your table contents, and select appearance and functionality options below.',
                    'municipio',
                ),
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_5731982808842',
                            'operator' => '==',
                            'value' => 'manual',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'tableclass' => '',
                'maxrows' => '',
                'disable_sort' => 0,
                'fixed_columns' => 0,
                'default_headers' => '',
                'default_header' => '',
                'readonly' => 0,
                'disabled' => 0,
                'sub_fields' => [],
            ],
            4 => [
                'key' => 'field_5666a459d2d2a',
                'label' => __('Aktivera sök', 'municipio'),
                'name' => 'mod_table_search',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => 50,
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'message' => __('Yes, use search on this table', 'municipio'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            5 => [
                'key' => 'field_56e181adef7ac',
                'label' => __('Aktivera kolumnsortering', 'municipio'),
                'name' => 'mod_table_ordering',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'message' => __('Yes, enable column sorting', 'municipio'),
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            6 => [
                'key' => 'field_6141aad011c4e',
                'label' => __('Multidimensional', 'municipio'),
                'name' => 'mod_table_multidimensional',
                'type' => 'true_false',
                'instructions' => __(
                    'Använd den första kolumnen som en andra dimension av tabellrubriker. Detta val låser också den första kolumnen vid scroll.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 1,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            7 => [
                'key' => 'field_6141b4af3a835',
                'label' => __('Sum', 'municipio'),
                'name' => 'mod_table_sum',
                'type' => 'true_false',
                'instructions' => __(
                    'Lägger till en rad i slutet av tabellen som summerar varje kolumns celler.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
            8 => [
                'key' => 'field_6141dc72e5dcd',
                'label' => __('Fullscreen', 'municipio'),
                'name' => 'mod_table_fullscreen',
                'type' => 'true_false',
                'instructions' => __(
                    'Renderar en ikon i högra hörnet som möjliggör helskärmsläge för tabellen.',
                    'municipio',
                ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-table',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ]);
}
