<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_60b8bf5bbc4d7',
    'title' => __('Table - Block settings', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_60b8c0d61b71e',
            'label' => __('Datatyp', 'modularity'),
            'name' => 'mod_table_data_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'manual' => __('Manual input', 'modularity'),
                'csv' => __('CSV Import', 'modularity'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => __('manual', 'modularity'),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        1 => array(
            'key' => 'field_60b9dd6efc445',
            'label' => __('CSV-fil', 'modularity'),
            'name' => 'mod_table_block_csv_file',
            'type' => 'file',
            'instructions' => __('CSV-formatterad fil', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_60b8c0d61b71e',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '.csv',
        ),
        2 => array(
            'key' => 'field_60b9dc81fc444',
            'label' => __('CSV-avgränsare', 'modularity'),
            'name' => 'mod_table_csv_delimiter',
            'type' => 'text',
            'instructions' => __('Tecken som används i CSV-filen som avgränsare. Brukar vara kommatecken eller semikolon.', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_60b8c0d61b71e',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __(';', 'modularity'),
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        3 => array(
            'key' => 'field_60b8c09f1b71d',
            'label' => __('Table', 'modularity'),
            'name' => 'mod_table',
            'type' => 'table',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_60b8c0d61b71e',
                        'operator' => '==',
                        'value' => 'manual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'use_header' => 0,
            'use_caption' => 2,
        ),
        4 => array(
            'key' => 'field_60b9def7b1bf4',
            'label' => __('Sidbläddring', 'modularity'),
            'name' => 'mod_table_pagination',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes, use pagination on this table', 'modularity'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_60b9df3d7f217',
            'label' => __('Antal inlägg/sidor', 'modularity'),
            'name' => 'mod_table_pagination_count',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_60b9def7b1bf4',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 10,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 1,
            'max' => 500,
            'step' => '',
        ),
        6 => array(
            'key' => 'field_60b9df727f218',
            'label' => __('Aktivera sök', 'modularity'),
            'name' => 'mod_table_search',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_60b9df987f219',
            'label' => __('Sökfras', 'modularity'),
            'name' => 'mod_table_search_query',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_60b9df727f218',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('Search in list', 'modularity'),
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        8 => array(
            'key' => 'field_60b9dfdf490d9',
            'label' => __('Aktivera kolumnsortering', 'modularity'),
            'name' => 'mod_table_ordering',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes, enable column sorting', 'modularity'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        9 => array(
            'key' => 'field_6141de4c43487',
            'label' => '',
            'name' => '',
            'type' => 'clone',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'clone' => array(
                0 => 'field_6141aad011c4e',
                1 => 'field_6141b4af3a835',
                2 => 'field_6141dc72e5dcd',
            ),
            'display' => 'seamless',
            'layout' => 'block',
            'prefix_label' => 0,
            'prefix_name' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/table',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}