<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_56a5e99108991',
    'title' => __('Slider', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_573dce058a66e',
            'label' => __('Slider ratio', 'modularity'),
            'name' => 'slider_format',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'ratio-36-7' => __('Wider (36:7)', 'modularity'),
                'ratio-10-3' => __('Wide (10:3)', 'modularity'),
                'ratio-16-9' => __('Normal (16:9, video)', 'modularity'),
                'ratio-4-3' => __('Square (4:3)', 'modularity'),
            ),
            'default_value' => __('ratio-16-9', 'modularity'),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
        1 => array(
            'key' => 'field_5731c6d886811',
            'label' => __('Autoslide', 'modularity'),
            'name' => 'slides_autoslide',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Slide automatically between views', 'modularity'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        2 => array(
            'key' => 'field_5731c78886813',
            'label' => __('Slide interval', 'modularity'),
            'name' => 'slides_slide_timeout',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731c6d886811',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 5,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('seconds', 'modularity'),
            'min' => 1,
            'max' => 20,
            'step' => 1,
        ),
        3 => array(
            'key' => 'field_633d95fb739ac',
            'label' => __('Number of slides shown per page', 'modularity'),
            'name' => 'slides_per_page',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_58933fb6f5ed4',
            'label' => __('Wrap around', 'modularity'),
            'name' => 'additional_options',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => __('If using videos in slides, this will option will not work.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'wrapAround' => __('Go to first slide when last item is reached', 'modularity'),
            ),
            'default_value' => array(
                0 => __('wrapAround', 'modularity'),
            ),
            'return_format' => 'value',
            'allow_custom' => 0,
            'layout' => 'horizontal',
            'toggle' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Add new choice',
        ),
        5 => array(
            'key' => 'field_56a5e994398d6',
            'label' => __('Slides', 'modularity'),
            'name' => 'slides',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                '56a5ed29398db' => array(
                    'key' => '56a5ed29398db',
                    'name' => 'image',
                    'label' => __('Bild', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5ed2f398dc',
                            'label' => __('Desktop image', 'modularity'),
                            'name' => 'image',
                            'aria-label' => '',
                            'type' => 'focuspoint',
                            'instructions' => __('This image will be used in larger screens. Preferably a widescreen image.', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'preview_size' => 'medium',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                        ),
                        1 => array(
                            'key' => 'field_56e7fa230ee09',
                            'label' => __('Template', 'modularity'),
                            'name' => 'textblock_position',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'bottom' => __('Bottom banner', 'modularity'),
                                'center' => __('Centered', 'modularity'),
                            ),
                            'default_value' => __('bottom', 'modularity'),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                            'create_options' => 0,
                            'save_options' => 0,
                        ),
                        2 => array(
                            'key' => 'field_5702597b7d869',
                            'label' => __('Title', 'modularity'),
                            'name' => 'textblock_title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'center',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'bottom',
                                    ),
                                ),
                                2 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'hero',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_56ab235393f04',
                            'label' => __('Content', 'modularity'),
                            'name' => 'textblock_content',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                            'acfe_textarea_code' => 0,
                        ),
                        4 => array(
                            'key' => 'field_56fa82a2d464d',
                            'label' => __('Link', 'modularity'),
                            'name' => 'link_type',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'false' => __('No link', 'modularity'),
                                'internal' => __('Internal', 'modularity'),
                                'external' => __('External', 'modularity'),
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => __('false', 'modularity'),
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        5 => array(
                            'key' => 'field_608915f2b15f7',
                            'label' => __('Link Style', 'modularity'),
                            'name' => 'link_style',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'cover' => __('Cover slide', 'modularity'),
                                'button' => __('Button', 'modularity'),
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => __('cover', 'modularity'),
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        6 => array(
                            'key' => 'field_60891647b15f8',
                            'label' => __('Link Text', 'modularity'),
                            'name' => 'link_text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_608915f2b15f7',
                                        'operator' => '==',
                                        'value' => 'button',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => __('Read More', 'modularity'),
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        7 => array(
                            'key' => 'field_56fa8313d4650',
                            'label' => __('Url', 'modularity'),
                            'name' => 'link_url',
                            'aria-label' => '',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        8 => array(
                            'key' => 'field_56fa8331d4651',
                            'label' => __('Page', 'modularity'),
                            'name' => 'link_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'allow_archives' => 1,
                            'multiple' => 0,
                        ),
                        9 => array(
                            'key' => 'field_60db1cc88b16d',
                            'label' => __('Description', 'modularity'),
                            'name' => 'link_url_description',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => __('Describe the purpose of the link, or what visitors can expect to find when they click on it (not shown).', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'acfe_flexible_render_template' => false,
                    'acfe_flexible_render_style' => false,
                    'acfe_flexible_render_script' => false,
                    'acfe_flexible_thumbnail' => false,
                    'acfe_flexible_settings' => false,
                    'acfe_flexible_settings_size' => 'medium',
                    'acfe_flexible_modal_edit_size' => false,
                    'acfe_flexible_category' => false,
                ),
                '56a5e9a5bbaf1' => array(
                    'key' => '56a5e9a5bbaf1',
                    'name' => 'video',
                    'label' => __('Video', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5eb09398d8',
                            'label' => __('Video: mp4', 'modularity'),
                            'name' => 'video_mp4',
                            'aria-label' => '',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'mp4',
                            'uploader' => '',
                        ),
                        1 => array(
                            'key' => 'field_56b9e2a221291',
                            'label' => __('Placeholder Image', 'modularity'),
                            'name' => 'image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 1140,
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg',
                            'uploader' => '',
                            'acfe_thumbnail' => 0,
                        ),
                        2 => array(
                            'key' => 'field_6007fbb665ed9',
                            'label' => __('Title', 'modularity'),
                            'name' => 'textblock_title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_56b9f3b8d7720',
                            'label' => __('Content', 'modularity'),
                            'name' => 'textblock_content',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                            'acfe_textarea_code' => 0,
                        ),
                        4 => array(
                            'key' => 'field_56e7fa620ee0a',
                            'label' => __('Text position', 'modularity'),
                            'name' => 'textblock_position',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56b9f3dba4f22',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                    1 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'bottom' => __('Bottom banner', 'modularity'),
                                'center' => __('Centered', 'modularity'),
                            ),
                            'default_value' => __('bottom', 'modularity'),
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                            'disabled' => 0,
                            'readonly' => 0,
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                            'create_options' => 0,
                            'save_options' => 0,
                        ),
                        5 => array(
                            'key' => 'field_6007f74a5f5a5',
                            'label' => __('Text color', 'modularity'),
                            'name' => 'text_color',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => __('What color to use on this slide', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'black' => __('Black', 'modularity'),
                                'white' => __('White', 'modularity'),
                                'theme' => __('Inherit theme', 'modularity'),
                            ),
                            'default_value' => __('black', 'modularity'),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                            'create_options' => 0,
                            'save_options' => 0,
                        ),
                        6 => array(
                            'key' => 'field_6007f6bf5f5a3',
                            'label' => __('Background color text area', 'modularity'),
                            'name' => 'background_color',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'none' => __('No background', 'modularity'),
                                'white' => __('White', 'modularity'),
                                'theme' => __('Inherit theme', 'modularity'),
                                'theme-opacity' => __('Inherit theme, add transparency', 'modularity'),
                            ),
                            'default_value' => __('white', 'modularity'),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                            'allow_custom' => 0,
                            'search_placeholder' => '',
                            'create_options' => 0,
                            'save_options' => 0,
                        ),
                        7 => array(
                            'key' => 'field_56fa87ec3ace2',
                            'label' => __('Link', 'modularity'),
                            'name' => 'link_type',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'false' => __('No link', 'modularity'),
                                'internal' => __('Intern', 'modularity'),
                                'external' => __('Extern', 'modularity'),
                            ),
                            'default_value' => __('false', 'modularity'),
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'layout' => 'horizontal',
                            'save_other_choice' => 0,
                        ),
                        8 => array(
                            'key' => 'field_646f76b08b955',
                            'label' => __('Link Style', 'modularity'),
                            'name' => 'link_style',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'cover' => __('Cover slide', 'modularity'),
                                'button' => __('Button', 'modularity'),
                            ),
                            'default_value' => __('cover', 'modularity'),
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'layout' => 'vertical',
                        ),
                        9 => array(
                            'key' => 'field_60080ae377d79',
                            'label' => __('Link text', 'modularity'),
                            'name' => 'link_text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_646f76b08b955',
                                        'operator' => '==',
                                        'value' => 'button',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => __('Read more', 'modularity'),
                            'maxlength' => 50,
                            'allow_in_bindings' => 1,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        10 => array(
                            'key' => 'field_56fa87fa3ace4',
                            'label' => __('Url', 'modularity'),
                            'name' => 'link_url',
                            'aria-label' => '',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        11 => array(
                            'key' => 'field_56fa88043ace5',
                            'label' => __('Page', 'modularity'),
                            'name' => 'link_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        12 => array(
                            'key' => 'field_646f745261c78',
                            'label' => __('Description', 'modularity'),
                            'name' => 'link_url_description',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'acfe_flexible_render_template' => false,
                    'acfe_flexible_render_style' => false,
                    'acfe_flexible_render_script' => false,
                    'acfe_flexible_thumbnail' => false,
                    'acfe_flexible_settings' => false,
                    'acfe_flexible_settings_size' => 'medium',
                    'acfe_flexible_modal_edit_size' => false,
                    'acfe_flexible_category' => false,
                ),
            ),
            'button_label' => __('Add slide', 'modularity'),
            'min' => 1,
            'max' => 6,
            'acfe_flexible_advanced' => false,
            'acfe_flexible_stylised_button' => false,
            'acfe_flexible_hide_empty_message' => false,
            'acfe_flexible_empty_message' => '',
            'acfe_flexible_layouts_templates' => false,
            'acfe_flexible_layouts_previews' => false,
            'acfe_flexible_layouts_placeholder' => false,
            'acfe_flexible_layouts_thumbnails' => false,
            'acfe_flexible_layouts_settings' => false,
            'acfe_flexible_async' => array(
            ),
            'acfe_flexible_add_actions' => array(
            ),
            'acfe_flexible_remove_button' => array(
            ),
            'acfe_flexible_layouts_state' => false,
            'acfe_flexible_modal_edit' => array(
                'acfe_flexible_modal_edit_enabled' => false,
                'acfe_flexible_modal_edit_size' => 'large',
            ),
            'acfe_flexible_modal' => array(
                'acfe_flexible_modal_enabled' => false,
                'acfe_flexible_modal_title' => false,
                'acfe_flexible_modal_size' => 'full',
                'acfe_flexible_modal_col' => '4',
                'acfe_flexible_modal_categories' => false,
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-slider',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/slider',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}