<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_59535d940706c',
        'title' => 'RSS',
        'fields' => [
            0 => [
                'key' => 'field_59535db89b29b',
                'label' => __('RSS feed URL', 'municipio'),
                'name' => 'rss_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
            ],
            1 => [
                'key' => 'field_59535e3782765',
                'label' => __('Number of items', 'municipio'),
                'name' => 'items',
                'type' => 'number',
                'instructions' => __('Set to -1 to show all', 'municipio'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ],
            2 => [
                'key' => 'field_595360d0232cc',
                'label' => __('Sort order', 'municipio'),
                'name' => 'sort_order',
                'type' => 'radio',
                'instructions' => __('Select order to sort the RSS feed', 'municipio'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'desc' => __('Descending', 'municipio'),
                    'asc' => __('Ascending', 'municipio'),
                ],
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ],
            3 => [
                'key' => 'field_59535e9382766',
                'label' => __('Fields', 'municipio'),
                'name' => 'fields',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'summary' => __('Summary', 'municipio'),
                    'author' => __('Author', 'municipio'),
                    'date' => __('Date', 'municipio'),
                ],
                'allow_custom' => 0,
                'save_custom' => 0,
                'default_value' => [],
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-rss',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);
}
