<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_56a89f42b432b',
    'title' => 'BookingFields',
    'fields' => array(
        0 => array(
            'display_format' => 'd/m/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
            'key' => 'field_56a89f4adc98d',
            'label' => __('Datum', 'modularity'),
            'name' => 'date',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_56a89fa0dc98e',
            'label' => __('Tid', 'modularity'),
            'name' => 'time',
            'type' => 'text',
            'instructions' => __('Ange tid', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        2 => array(
            'default_value' => '',
            'min' => '',
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_56a89fdddc98f',
            'label' => __('Pris', 'modularity'),
            'name' => 'price',
            'type' => 'number',
            'instructions' => __('Ange pris', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        3 => array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_56a8a005dc990',
            'label' => __('Alternativ pris', 'modularity'),
            'name' => 'alternative_price',
            'type' => 'text',
            'instructions' => __('Om det finns ett ungdoms, eller ett rabatterat pris går det att ange här', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        4 => array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_56a8a040dc991',
            'label' => __('Rubrik köpknapp', 'modularity'),
            'name' => 'title_buy_button',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        5 => array(
            'default_value' => '',
            'placeholder' => '',
            'key' => 'field_56a8a095dc992',
            'label' => __('Länk till webbshop', 'modularity'),
            'name' => 'link_to_webbshop',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-booking',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1453900881,
    'local' => 'json',
));
}