<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_571dfd3c07a77',
    'title' => __('Data display', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_571dfd4c0d9d9',
            'label' => __('Display as', 'modularity'),
            'name' => 'posts_display_as',
            'aria-label' => '',
            'type' => 'image_select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '6762ed43da0e4' => array(
                    'image-select-repeater-label' => 'Accordion',
                    'image-select-repeater-value' => 'expandable-list',
                ),
                '6762eee7da0e7' => array(
                    'image-select-repeater-label' => 'Block',
                    'image-select-repeater-value' => 'grid',
                ),
                '6762eeeeda0e8' => array(
                    'image-select-repeater-label' => 'Box',
                    'image-select-repeater-value' => 'features-grid',
                ),
                '6762eef4da0e9' => array(
                    'image-select-repeater-label' => 'Card',
                    'image-select-repeater-value' => 'index',
                ),
                '6762eefeda0ea' => array(
                    'image-select-repeater-label' => 'Collection',
                    'image-select-repeater-value' => 'collection',
                ),
                '6762ef12da0eb' => array(
                    'image-select-repeater-label' => 'List',
                    'image-select-repeater-value' => 'list',
                ),
                '6762ef6ada0ec' => array(
                    'image-select-repeater-label' => 'News',
                    'image-select-repeater-value' => 'news',
                ),
                '6762ef74da0ed' => array(
                    'image-select-repeater-label' => 'Segment',
                    'image-select-repeater-value' => 'segment',
                ),
            ),
        ),
        1 => array(
            'key' => 'field_6762ecffda0e3',
            'label' => __('posts_display_as_conditional', 'modularity'),
            'name' => 'posts_display_as_conditional',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'acf-hidden',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        2 => array(
            'key' => 'field_67813612eb109',
            'label' => __('Allow logged in users to modify their list', 'modularity'),
            'name' => 'allow_user_modification',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        3 => array(
            'key' => 'field_678665cc4cc6e',
            'label' => __('Save as custom meta key', 'modularity'),
            'name' => 'save_as_custom_meta_key',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('Will default to the module ID but can be set to save as a custom meta key.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_67813612eb109',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '70',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => __('unique-key', 'modularity'),
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_675c0e6f7becc',
            'label' => __('Use term icon as icon in list', 'modularity'),
            'name' => 'use_term_icon_as_icon_in_list',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_636249fee87cc',
            'label' => __('Preamble', 'modularity'),
            'name' => 'preamble',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        6 => array(
            'key' => 'field_68469afc46fa3',
            'label' => __('Open links in new tab', 'modularity'),
            'name' => 'posts_open_links_in_new_tab',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('How a link should open (new tab or in current tab)', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'external' => __('External', 'modularity'),
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'placeholder' => __('None', 'modularity'),
            'allow_null' => 1,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        7 => array(
            'key' => 'field_6356477fbc5e4',
            'label' => __('Show as slider', 'modularity'),
            'name' => 'show_as_slider',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        8 => array(
            'key' => 'field_6418289cf23a6',
            'label' => __('Image position', 'modularity'),
            'name' => 'image_position',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'segment',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                1 => __('Left', 'modularity'),
                0 => __('Right', 'modularity'),
            ),
            'default_value' => 1,
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        9 => array(
            'key' => 'field_628e0ffba7da4',
            'label' => __('Highlight first post', 'modularity'),
            'name' => 'posts_highlight_first',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Makes the first post bigger', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'segment',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'list',
                    ),
                    2 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'features-grid',
                    ),
                    3 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                    4 => array(
                        'field' => 'field_6356477fbc5e4',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        10 => array(
            'key' => 'field_629f1b34ef9fc',
            'label' => __('Display highlighted post as', 'modularity'),
            'name' => 'posts_display_highlighted_as',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_628e0ffba7da4',
                        'operator' => '==',
                        'value' => '1',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'news',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'block' => __('Block', 'modularity'),
                'card' => __('Card', 'modularity'),
            ),
            'default_value' => __('block', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        11 => array(
            'key' => 'field_571dfdf50d9da',
            'label' => __('Columns', 'modularity'),
            'name' => 'posts_columns',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'grid-md-12' => __('1', 'modularity'),
                'grid-md-6' => __('2', 'modularity'),
                'grid-md-4' => __('3', 'modularity'),
                'grid-md-3' => __('4', 'modularity'),
            ),
            'default_value' => __('grid-md-12', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        12 => array(
            'key' => 'field_571e01e7f246c',
            'label' => __('Fields', 'modularity'),
            'name' => 'posts_fields',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'expandable-list',
                    ),
                    1 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '!=',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'date' => __('Show date', 'modularity'),
                'excerpt' => __('Show excerpt', 'modularity'),
                'title' => __('Show title', 'modularity'),
                'image' => __('Show featured image', 'modularity'),
                'reading_time' => __('Show reading time', 'modularity'),
                'comment_count' => __('Comment count', 'modularity'),
            ),
            'default_value' => array(
                0 => __('date', 'modularity'),
                1 => __('excerpt', 'modularity'),
                2 => __('title', 'modularity'),
                3 => __('image', 'modularity'),
            ),
            'return_format' => 'value',
            'allow_custom' => 0,
            'layout' => 'horizontal',
            'toggle' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Lägg till nytt val',
        ),
        13 => array(
            'key' => 'field_591176fff96d6',
            'label' => __('Hide the title column', 'modularity'),
            'name' => 'posts_hide_title_column',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'expandable-list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes, hide the title column', 'modularity'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        14 => array(
            'key' => 'field_57e3bcae3826e',
            'label' => __('Title column label', 'modularity'),
            'name' => 'title_column_label',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'expandable-list',
                    ),
                    1 => array(
                        'field' => 'field_591176fff96d6',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        15 => array(
            'key' => 'field_571f5776592e6',
            'label' => __('List column labels', 'modularity'),
            'name' => 'posts_list_column_titles',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('A title field will always be added as the first column. You will need to go to each post in this list to give the values for each column.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'expandable-list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'modularity'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_571f5790592e7',
                    'label' => __('Column header', 'modularity'),
                    'name' => 'column_header',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                    'parent_repeater' => 'field_571f5776592e6',
                ),
            ),
        ),
        16 => array(
            'key' => 'field_59197c6dafb31',
            'label' => __('Allow freetext filtering', 'modularity'),
            'name' => 'allow_freetext_filtering',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'expandable-list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Allow freetext filtering', 'modularity'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        17 => array(
            'key' => 'field_5be480e163246',
            'label' => __('Highlight post', 'modularity'),
            'name' => 'posts_highlight',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'list',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => __('Enabled', 'modularity'),
            'ui_off_text' => __('Disabled', 'modularity'),
            'ui' => 1,
        ),
        18 => array(
            'key' => 'field_5bd8575106176',
            'label' => __('Placeholder image', 'modularity'),
            'name' => 'posts_placeholder',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'list',
                    ),
                    1 => array(
                        'field' => 'field_571e01e7f246c',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'return_format' => 'array',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        19 => array(
            'key' => 'field_628e0f242aa5f',
            'label' => __('Ratio', 'modularity'),
            'name' => 'ratio',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'grid',
                    ),
                ),
                1 => array(
                    0 => array(
                        'field' => 'field_6762ecffda0e3',
                        'operator' => '==',
                        'value' => 'features-grid',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '1:1' => __('1:1', 'modularity'),
                '4:3' => __('4:3', 'modularity'),
                '12:16' => __('12:16', 'modularity'),
            ),
            'default_value' => '4:3',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-posts',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/posts',
            ),
        ),
    ),
    'menu_order' => -10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}