<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_570770ab8f064',
        'title' => __('Image', 'municipio'),
        'fields' => [
            0 => [
                'key' => 'field_570770b8e2e61',
                'label' => __('Image', 'municipio'),
                'name' => 'mod_image_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => __('Allowed file types: jpg, png, gif', 'municipio'),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'uploader' => '',
                'return_format' => 'id',
                'acfe_thumbnail' => 0,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => 'jpg, png, gif',
                'preview_size' => 'medium',
                'library' => 'all',
            ],
            1 => [
                'key' => 'field_587604df2975f',
                'label' => __('Image caption', 'municipio'),
                'name' => 'mod_image_caption',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'new_lines' => 'br',
                'maxlength' => '',
                'placeholder' => '',
                'rows' => 4,
                'acfe_textarea_code' => 0,
            ],
            2 => [
                'key' => 'field_577d07c8d72db',
                'label' => __('Link', 'municipio'),
                'name' => 'mod_image_link',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'horizontal',
                'choices' => [
                    'false' => __('None', 'municipio'),
                    'internal' => __('Internal', 'municipio'),
                    'external' => __('External', 'municipio'),
                ],
                'default_value' => '',
                'other_choice' => 0,
                'save_other_choice' => 0,
                'allow_null' => 0,
                'return_format' => 'value',
            ],
            3 => [
                'key' => 'field_577d0810d72dc',
                'label' => __('Link url', 'municipio'),
                'name' => 'mod_image_link_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_577d07c8d72db',
                            'operator' => '==',
                            'value' => 'external',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
            ],
            4 => [
                'key' => 'field_577d0840d72dd',
                'label' => __('Link page', 'municipio'),
                'name' => 'mod_image_link_url',
                'aria-label' => '',
                'type' => 'page_link',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_577d07c8d72db',
                            'operator' => '==',
                            'value' => 'internal',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'allow_archives' => 1,
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-image',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/image',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
