@extends('templates.master')
@section('layout')
    @switch($activeSearchEngine)
        @case("google")
            @include('partials.search.google')
            @break
        @case("algolia")
            @include('partials.search.algolia')
            @break
        @default
            @include('partials.search.wp')
    @endswitch
@stop
