<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57bb00ff522ad',
    'title' => __('Incident list', 'municipio-intranet'),
    'fields' => array(
        0 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'all' => __('All', 'municipio-intranet'),
                'subscriptions' => __('Subscriptions', 'municipio-intranet'),
                'current' => __('Current', 'municipio-intranet'),
            ),
            'default_value' => 'all',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_57bb010350df3',
            'label' => __('Incidents from', 'municipio-intranet'),
            'name' => 'incidents',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'all' => __('All', 'municipio-intranet'),
                'info' => __('Low', 'municipio-intranet'),
                'warning' => __('Medium', 'municipio-intranet'),
                'danger' => __('High', 'municipio-intranet'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_57bb013450df4',
            'label' => __('Incident level', 'municipio-intranet'),
            'name' => 'incident_level',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'default_value' => 5,
            'min' => '',
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_57bb017e50df5',
            'label' => __('Length', 'municipio-intranet'),
            'name' => 'length',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        3 => array(
            'default_value' => 0,
            'message' => __('Yes, link to archive', 'municipio-intranet'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_57bb019750df6',
            'label' => __('Link to archive', 'municipio-intranet'),
            'name' => 'link_to_archive',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-intranet-inciden',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}